const f=(name,en,id,type='text',options)=>[name,en,id,type,options];
const title=f('title','Title','Judul'), owner=f('ownerId','Owner','Penanggung jawab','member'), due=f('dueDate','Due date','Tenggat','date'), project=f('projectId','Project','Proyek','project'), notes=f('notes','Notes','Catatan','textarea'), stage=f('stageId','Stage','Tahap','stage');
export const DIVISION_VIEWS=[
 {slug:'strategy-growth',name:'Strategy & Growth',id:'Strategi & Pertumbuhan',icon:'compass',subtitle:['Turn direction into a clear next step.','Ubah arah menjadi langkah berikutnya yang jelas.'],collections:['initiatives','decisions','dependencies']},
 {slug:'human-resource',name:'Human Resource',id:'Sumber Daya Manusia',icon:'people',subtitle:['A thoughtful journey for every member.','Perjalanan yang terarah untuk setiap anggota.'],collections:['candidates','onboarding','assignments','development']},
 {slug:'external-engagement',name:'External Engagement',id:'Hubungan Eksternal',icon:'globe',subtitle:['Keep relationships moving forward.','Jaga hubungan dan tindak lanjut tetap berjalan.'],collections:['partners','followups']},
 {slug:'marketing-comms-it',name:'Marketing, Communication & IT',id:'Pemasaran, Komunikasi & TI',icon:'sparkles',subtitle:['From the first idea to the final release.','Dari ide pertama hingga rilis akhir.'],collections:['deliverables','campaigns','itDeliveries','assets']},
 {slug:'legal-finance',name:'Legal & Finance',id:'Legal & Keuangan',icon:'wallet',subtitle:['Every request, document, and rupiah in context.','Setiap permintaan, dokumen, dan rupiah dalam konteks.'],collections:['financeRequests','budgets','legalRequests']},
 {slug:'consulting',name:'Consulting',id:'Konsultasi',icon:'briefcase',subtitle:['Bring clarity to the work you deliver.','Perjelas pekerjaan dan hasil yang disampaikan.'],collections:['deliveries']},
];
export const GROUP_FOR={initiatives:'initiatives',financeRequests:'financeRequests',candidates:'recruitment',onboarding:'onboarding',deliverables:'content',itDeliveries:'itDelivery'};
export const DIVISION_SCHEMAS={
 initiatives:{labels:{en:'Initiatives',id:'Inisiatif'},fields:[title,f('horizon','Horizon','Horizon','select',[['now','Now','Sekarang'],['next','Next','Berikutnya'],['later','Later','Nanti']]),stage,owner,project,due,f('researchUrl','Research link','Tautan riset','url'),f('summary','Purpose and evidence','Tujuan dan bukti','textarea')]},
 decisions:{labels:{en:'Decisions',id:'Keputusan'},fields:[title,owner,due,f('status','Status','Status','select',[['pending','Pending','Menunggu'],['decided','Decided','Diputuskan']]),f('outcome','Outcome and rationale','Hasil dan alasan','textarea')]},
 dependencies:{labels:{en:'Dependencies',id:'Dependensi'},fields:[title,project,f('toDivision','Waiting on division','Menunggu divisi','division'),due,f('status','Status','Status','select',[['waiting','Waiting','Menunggu'],['ready','Ready','Siap'],['resolved','Resolved','Selesai']]),f('detail','What is needed','Yang dibutuhkan','textarea')]},
 budgets:{labels:{en:'Budgets',id:'Anggaran'},fields:[title,project,f('category','Category','Kategori'),f('allocated','Allocated (IDR)','Alokasi (IDR)','number')]},
 financeRequests:{labels:{en:'Requests',id:'Permintaan'},fields:[title,f('type','Request type','Jenis permintaan','select',[['expense','Expense','Pengeluaran'],['budget','Budget allocation','Alokasi anggaran'],['legal','Legal','Legal']]),stage,f('budgetId','Budget line','Pos anggaran','budget'),project,f('amount','Amount (IDR)','Jumlah (IDR)','number'),f('category','Category','Kategori'),f('requesterId','Requested by','Pemohon','member'),f('approverId','Reviewed by','Peninjau','member'),due,f('documentUrl','Document / receipt link','Tautan dokumen / bukti','url'),f('details','Details','Rincian','textarea')]},
 candidates:{labels:{en:'Recruitment',id:'Rekrutmen'},fields:[title,f('role','Role','Peran'),stage,owner,due,notes]},
 onboarding:{labels:{en:'Onboarding',id:'Orientasi'},fields:[title,f('memberId','Member','Anggota','member'),stage,owner,due,notes]},
 assignments:{labels:{en:'Assignments',id:'Penugasan'},fields:[title,f('memberId','Member','Anggota','member'),owner,project,due,f('status','Status','Status','select',[['open','Open','Terbuka'],['complete','Complete','Selesai']]),notes]},
 development:{labels:{en:'Development',id:'Pengembangan'},fields:[title,f('memberId','Member','Anggota','member'),owner,due,f('status','Status','Status','select',[['planned','Planned','Direncanakan'],['active','Active','Aktif'],['complete','Complete','Selesai']]),notes]},
 campaigns:{labels:{en:'Campaigns',id:'Kampanye'},fields:[title,f('channel','Channel','Kanal'),owner,f('startDate','Start date','Tanggal mulai','date'),f('endDate','End date','Tanggal akhir','date'),f('summary','Brief','Ringkasan','textarea')]},
 deliverables:{labels:{en:'Content',id:'Konten'},fields:[title,f('campaignId','Campaign','Kampanye','campaign'),stage,owner,f('publishDate','Publish date','Tanggal terbit','date'),f('channel','Channel','Kanal'),f('assetUrl','Asset link','Tautan aset','url'),f('publishedUrl','Published link','Tautan publikasi','url'),notes]},
 itDeliveries:{labels:{en:'IT delivery',id:'Pekerjaan TI'},fields:[title,stage,owner,project,due,notes]},
 assets:{labels:{en:'Assets',id:'Aset'},fields:[title,f('kind','Type','Jenis'),f('campaignId','Campaign','Kampanye','campaign'),f('url','Asset link','Tautan aset','url'),notes]},
};
export const EXTRA_SCHEMAS={
 milestones:{labels:{en:'Milestones',id:'Tonggak'},fields:[title,f('due_date','Target date','Tanggal target','date'),f('owner_id','Owner','Penanggung jawab','member'),f('status','Status','Status','select',[['planned','Planned','Direncanakan'],['at_risk','At risk','Berisiko'],['reached','Reached','Tercapai']])]},
 blockers:{labels:{en:'Blockers',id:'Hambatan'},fields:[title,f('description','What is blocked','Yang terhambat','textarea'),f('severity','Severity','Tingkat','select',[['low','Low','Rendah'],['medium','Medium','Sedang'],['high','High','Tinggi']]),f('owner_id','Resolution owner','Penanggung jawab solusi','member'),f('task_id','Affected task','Tugas terdampak','task'),f('milestone_id','Affected milestone','Tonggak terdampak','milestone'),f('requested_action','Action needed','Tindakan diperlukan','textarea'),f('target_resolution_date','Target resolution','Target penyelesaian','date'),f('resolved','Resolved','Selesai','checkbox'),f('resolution_note','Resolution note','Catatan penyelesaian','textarea')]},
 dependencies:{labels:{en:'Dependencies',id:'Dependensi'},fields:[f('depends_on_id','Depends on project','Bergantung pada proyek','project'),f('note','What is needed','Yang dibutuhkan','textarea')]},
 decisions:{labels:{en:'Decisions',id:'Keputusan'},fields:[f('decision','Decision','Keputusan','textarea'),f('rationale','Reason and context','Alasan dan konteks','textarea'),f('decided_at','Decision date','Tanggal keputusan','date'),f('supersedes_id','Supersedes decision','Menggantikan keputusan','decision')]},
 documents:{labels:{en:'Documents',id:'Dokumen'},fields:[title,f('external_url','Document link','Tautan dokumen','url'),f('version_label','Version','Versi'),f('notes','Description','Deskripsi','textarea')]},
};
export const STAGE_TRANSLATIONS={'Not started':'Belum dimulai','In progress':'Sedang berjalan','Completed':'Selesai','Blocked':'Terhambat','Proposed':'Diusulkan','Researching':'Dalam riset','Active':'Aktif','Paused':'Dijeda','Draft':'Draf','Submitted':'Diajukan','In review':'Dalam tinjauan','Approved':'Disetujui','Rejected':'Ditolak','Paid':'Dibayar','Applied':'Mendaftar','Screening':'Seleksi','Interview':'Wawancara','Offer':'Penawaran','Joined':'Bergabung','Closed':'Ditutup','Waiting':'Menunggu','Complete':'Selesai','Idea':'Ide','Producing':'Produksi','Scheduled':'Terjadwal','Published':'Diterbitkan','Planned':'Direncanakan','Building':'Dikerjakan','Review':'Tinjauan','Released':'Dirilis','Pending':'Menunggu','High':'Tinggi','Medium':'Sedang','Low':'Rendah'};
