import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url));
const files=['sections-foundation.json','sections-detail.json','sections-changes.json'];
for(const f of files){const nodes=JSON.parse(fs.readFileSync(path.join(here,f),'utf8'));for(const n of nodes){for(const field of ['notes','source','acceptance','title'])if(typeof n[field]==='string')n[field]=n[field].replaceAll('as close to Rp0/month as possible','target Rp35,000/month, hard ceiling Rp50,000/month').replaceAll('near-zero monthly budget','monthly target Rp35,000 and ceiling Rp50,000').replaceAll('Confirmed budget near Rp0.','Confirmed budget target Rp35,000/month, hard ceiling Rp50,000/month.').replaceAll('near-zero-cost','budget-limited').replaceAll('near-zero limits','Rp35,000 target / Rp50,000 ceiling').replaceAll('near-zero budget','Rp35,000 target and Rp50,000 ceiling').replaceAll('user zero-budget constraint','user Rp35,000 target / Rp50,000 ceiling').replaceAll('User zero-budget answer','User revised budget: target Rp35,000/month, maximum Rp50,000/month').replaceAll('current minimum cost constraint','current Rp35,000 target / Rp50,000 ceiling');
if(n.id==='root')n.source+='; latest user budget correction: target Rp35,000/month, maximum Rp50,000/month';
if(n.id==='design-project-tabs')n.notes=n.notes.replace('internal folders, uploads, linked documents/apps','internal folders, linked documents/apps, and later optional uploads');
if(n.id==='decision-free-tradeoff'){n.title='Can the operating plan fit Rp35,000–Rp50,000/month?';n.notes='Confirmed budget target Rp35,000/month, hard ceiling Rp50,000/month. Proposed baseline uses low-cost eligible managed services and a free subdomain, with independently tested backup/custody. Use the budget for necessary recurring operations rather than spending to reach a target. Resolve vendor inactivity/quota limits, actual backup destination costs, annualized charges and response ownership. Supabase Pro is outside this ceiling at checked pricing and needs a separate future budget decision. Small optional paid services must fit the all-in ceiling, including taxes/card fees and annual renewals. Affordable service is not a promise of always-on availability.';}
if(n.id==='decision-file-policy'){n.notes='Default launch Resources uses native notes/folders and links to external files; native binary upload is deferred unless explicitly enabled after storage/cost/security approval. The user has no current shared Drive. Arrange organization custody with named operators and individual sharing; distinguish Shared Drive entitlement from an ordinary shared folder. Review existing personal-file links and ownership continuity before import. No shared-account password distribution. Any optional provider charge/annual renewal counts toward target Rp35,000 and maximum Rp50,000/month.';n.acceptance='Choose provider/ownership, successor access, sensitive-resource policy and departure process before real import; keep native uploads disabled until explicitly accepted.';}
if(n.id==='integration-previews'){n.status='deferred';n.priority='P2';n.notes='Default launch opens authorized external provider links; provider-supported embeds are optional and must respect permissions/browser restrictions. Native uploaded-file preview is deferred with binary upload, not a launch dependency. If later enabled, define small MIME/size limits, safe isolation and download fallback; never render untrusted HTML in the app origin. Missing/denied external links preserve metadata and offer an access-request route.';}
if(n.id==='quality-backup-proof'){n.notes='Produce a record/native-note snapshot with schema/version and external-link manifest, restore to an isolated target, reconcile counts and relationships, and open sample records/notes/metadata. External-provider document bytes are not backed up by a link manifest or database dump. Adopt a separate provider-file continuity/export policy before relying on those documents. If native uploads are later enabled, add file bytes/checksum restore proof. Recovery evidence names operator, excluded scope, snapshot age and actual elapsed time.';}
if(n.id==='quality-journey-matrix')n.notes=n.notes.replace('folder→link/file/note','folder→external-file link/native note');
}fs.writeFileSync(path.join(here,f),JSON.stringify(nodes,null,2));}
for(const f of ['README.md']){const p=path.join(here,f);let s=fs.readFileSync(p,'utf8');s=s.replaceAll('Budget as close to Rp0 per month as possible','Budget target Rp35,000/month and hard ceiling Rp50,000/month').replaceAll('Free-tier suitability','The budget-limited stack’s suitability');fs.writeFileSync(p,s);}
const agents=path.resolve(here,'../../AGENTS.md');let instructions=fs.readFileSync(agents,'utf8');instructions=instructions.replace('near-zero budget','monthly Rp35,000 target and Rp50,000 ceiling');fs.writeFileSync(agents,instructions);
console.log('Updated current budget and conditional upload/recovery scope in parent-owned planning files.');
