import { Window } from 'happy-dom';
import fs from 'node:fs';
import assert from 'node:assert/strict';
import { validateWorkspace } from './planner-store.mjs';

const source=fs.readFileSync(new URL('./planner.mjs',import.meta.url),'utf8');
const html=fs.readFileSync(new URL('./planner.html',import.meta.url),'utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'');
const clone=value=>JSON.parse(JSON.stringify(value));
function fixture(){return {kind:'dwdg-one-planning-workspace',schemaVersion:1,revision:0,updatedAt:'2026-10-05T00:00:00.000Z',notes:'Planning only',customMetadata:{tool:'Claude'},prd:{kind:'dwdg-one-prd',schemaVersion:1,seedVersion:'2026-10-03-v1',title:"DWDG'ONE",externalContext:{origin:'Other AI'},nodes:[{id:'root',parent:null,title:"DWDG'ONE",notes:'Working draft',owner:'Mahdy',source:'User',acceptance:'Every node editable',status:'confirmed',priority:'P0',dependencies:''},{id:'hr',parent:'root',title:'HR monitoring',notes:'One cycle every fourteen days',owner:'HR',source:'User',acceptance:'14-day cycle',status:'confirmed',priority:'P0',dependencies:'',externalTool:{label:'Keep'}}]},wbs:[{id:'work',parent:null,title:'HR work package',deliverable:'Monitoring process',owner:'HR',acceptance:'Grading cycle specified',requirementIds:['hr'],dependsOn:[],priority:'P0',estimateHours:null,release:'v1',externalLabel:'Preserve this'}],activities:[{id:'monitor',title:'Monitor membership',order:1}],stories:[{id:'story',activityId:'monitor',actor:'HR',action:'review fortnightly monitoring',benefit:'members receive feedback',acceptance:'One cycle every 14 days',requirementIds:['hr'],wbsId:'work',release:'v1',priority:'P0',order:1}],cards:[{id:'card',title:'Specify monitoring',description:'Capture grading and review policy',status:'backlog',priority:'P0',owner:'HR',acceptance:'Rubric reviewed',wbsId:'work',requirementIds:['hr'],storyIds:['story'],dependsOn:[],release:'v1',evidence:'',customCardField:'Preserve'}],history:[]};}
const windows=[];
const tick=async()=>{for(let i=0;i<12;i++)await Promise.resolve();};
async function start(options={}){const w=new Window({url:'http://127.0.0.1:5174/',settings:{disableJavaScriptFileLoading:true,disableCSSFileLoading:true,disableIframePageLoading:true}});windows.push(w);w.TextEncoder=TextEncoder;w.confirm=()=>true;w.Element.prototype.scrollIntoView=function(){};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};let clock=0,next=1,stored=fixture(),etag='etag-0',held=null,heldPoll=null,getCount=0;const timers=new Map(),requests=[],intervals=[];validateWorkspace(stored);w.setTimeout=(fn,delay=0)=>{const id=next++;timers.set(id,{fn,at:clock+delay});return id;};w.clearTimeout=id=>timers.delete(id);w.setInterval=fn=>{intervals.push(fn);return intervals.length;};w.clearInterval=()=>{};
  const response=(status,body)=>({ok:status>=200&&status<300,status,json:async()=>clone(body),text:async()=>String(body)});
  function accept(payload){validateWorkspace(payload.document);stored=clone(payload.document);stored.revision++;stored.updatedAt=new Date().toISOString();stored.history=[...stored.history,{id:'change-'+stored.revision,at:stored.updatedAt,actor:payload.actor,action:'edit',summary:payload.summary,changes:[]}];etag='etag-'+stored.revision;return response(200,{document:stored,etag});}
  w.fetch=async(url,init={})=>{url=String(url);if(url==='/editor-shell.html')return response(200,'<div>Requirement editor fixture</div>');if(url==='/api/workspace'&&(init.method||'GET')==='GET'){getCount++;if(options.holdPoll&&getCount===2){const snapshot={document:clone(stored),etag};return new Promise(resolve=>{heldPoll=()=>resolve(response(200,snapshot));});}return response(200,{document:stored,etag});}if(url==='/api/workspace'&&init.method==='PUT'){const payload=JSON.parse(init.body);requests.push(payload);if(options.conflict)return response(409,{error:'The saved file changed'});if(options.holdFirst&&requests.length===1)return new Promise(resolve=>{held=()=>resolve(accept(payload));});try{return accept(payload);}catch(error){return response(422,{error:error.message});}}if(url==='/api/validate'){try{const input=JSON.parse(init.body),document=input.document||input;validateWorkspace(document);return response(200,{valid:true,document});}catch(error){return response(422,{error:error.message});}}throw new Error('Unexpected API request '+url);};
  w.document.body.innerHTML=html;w.eval(source);await tick();
  return {w,requests,get stored(){return clone(stored);},get held(){return held;},get heldPoll(){return heldPoll;},poll:()=>intervals[0]?.(),async advance(ms=500){clock+=ms;let cycles=0;while([...timers.values()].some(t=>t.at<=clock)){if(++cycles>100)throw new Error('Unexpected repeated timer');const entries=[...timers.entries()].filter(([,t])=>t.at<=clock);for(const [id,timer]of entries){if(!timers.has(id))continue;timers.delete(id);timer.fn();}await tick();}await tick();},async settle(){await tick();},close:()=>w.happyDOM.abort()};}
const $=(ctx,selector)=>ctx.w.document.querySelector(selector);
function click(ctx,selector){const el=$(ctx,selector);assert.ok(el,'Missing '+selector);el.click();}
function form(ctx,name,value){const el=$(ctx,'#item-fields [name="'+name+'"]');assert.ok(el,'Missing form field '+name);el.value=value;el.dispatchEvent(new ctx.w.Event('input',{bubbles:true}));}
function submit(ctx){$(ctx,'#item-form').dispatchEvent(new ctx.w.Event('submit',{bubbles:true,cancelable:true}));}
function status(ctx,value){const el=$(ctx,'[data-move-card="card"]');assert.ok(el);el.value=value;el.dispatchEvent(new ctx.w.Event('change',{bubbles:true}));}
let checks=0;
async function check(name,fn){await fn();checks++;console.log('PASS '+name);}
const c=await start();
await check('Opening reads the shared saved file and renders the requirement count',()=>{assert.match($(c,'#document-summary').textContent,/2 requirements/);assert.match($(c,'#save-status').textContent,/Saved to project file/);assert.equal(c.requests.length,0);});
await check('Kanban status autosaves a file PUT with actor and revision guard',async()=>{click(c,'[data-view="kanban"]');status(c,'ready');assert.match($(c,'#save-status').textContent,/Unsaved changes/);await c.advance();assert.equal(c.requests.length,1);assert.equal(c.requests[0].baseEtag,'etag-0');assert.equal(c.requests[0].actor,'Local editor');assert.equal(c.stored.cards[0].status,'ready');assert.equal(c.stored.cards[0].customCardField,'Preserve');assert.match($(c,'#save-status').textContent,/Saved to project file/);});
await check('Done requires evidence and preserves the previous status until valid save',async()=>{status(c,'done');assert.equal(c.stored.cards[0].status,'ready');assert.equal($(c,'#item-dialog').open,true);assert.match($(c,'#form-error').textContent,/completion evidence/);submit(c);assert.match($(c,'#form-error').textContent,/completion evidence/);form(c,'evidence','Reviewed rubric at docs/hr-rubric.md');submit(c);await c.advance();assert.equal(c.stored.cards[0].status,'done');assert.match(c.stored.cards[0].evidence,/Reviewed rubric/);});
await check('WBS add, edit and delete persist without resetting linked work',async()=>{click(c,'[data-view="wbs"]');click(c,'[data-action="add"][data-kind="wbs"]');form(c,'title','Recovery package');form(c,'deliverable','A tested restore drill');form(c,'acceptance','1. Restore completes within 30 minutes');form(c,'owner','IT');submit(c);await c.advance();const added=c.stored.wbs.find(w=>w.title==='Recovery package');assert.ok(added);click(c,'[data-action="edit"][data-kind="wbs"][data-id="'+added.id+'"]');form(c,'title','Recovery operations');submit(c);await c.advance();assert.equal(c.stored.wbs.find(w=>w.id===added.id).title,'Recovery operations');click(c,'[data-action="edit"][data-kind="wbs"][data-id="'+added.id+'"]');click(c,'[data-action="delete-item"]');await c.advance();assert.equal(c.stored.wbs.length,1);assert.equal(c.stored.cards[0].wbsId,'work');});
await check('Story add, edit and delete save the actor/action/benefit map',async()=>{click(c,'[data-view="stories"]');click(c,'[data-action="add"][data-kind="stories"]');form(c,'actor','Member');form(c,'action','declare unavailable time');form(c,'benefit','meetings respect consented schedules');form(c,'acceptance','1. Availability interval survives reload');form(c,'requirementIds','hr');submit(c);await c.advance();const story=c.stored.stories.find(s=>s.actor==='Member');assert.ok(story);assert.equal(story.activityId,'monitor');click(c,'[data-action="edit"][data-kind="stories"][data-id="'+story.id+'"]');form(c,'action','edit my unavailable interval');submit(c);await c.advance();assert.match(c.stored.stories.find(s=>s.id===story.id).action,/edit my/);click(c,'[data-action="edit"][data-kind="stories"][data-id="'+story.id+'"]');click(c,'[data-action="delete-item"]');await c.advance();assert.equal(c.stored.stories.length,1);});
await check('Deleting referenced packages, stories and activities is blocked explicitly',()=>{click(c,'[data-view="wbs"]');click(c,'[data-action="edit"][data-kind="wbs"][data-id="work"]');click(c,'[data-action="delete-item"]');assert.match($(c,'#form-error').textContent,/Unlink these items/);assert.match($(c,'#form-error').textContent,/card/);click(c,'[data-action="close-editor"]');click(c,'[data-view="stories"]');click(c,'[data-action="edit"][data-kind="stories"][data-id="story"]');click(c,'[data-action="delete-item"]');assert.match($(c,'#form-error').textContent,/card/);click(c,'[data-action="close-editor"]');click(c,'[data-action="edit"][data-kind="activities"][data-id="monitor"]');click(c,'[data-action="delete-item"]');assert.match($(c,'#form-error').textContent,/story/);click(c,'[data-action="close-editor"]');assert.equal(c.stored.wbs.length,1);assert.equal(c.stored.stories.length,1);assert.equal(c.stored.activities.length,1);});
await check('Empty filters clear visible cards and Reset restores them',()=>{click(c,'[data-view="kanban"]');$(c,'#search').value='zero nonexistent matches';$(c,'#search').dispatchEvent(new c.w.Event('input',{bubbles:true}));assert.equal(c.w.document.querySelectorAll('[data-card]').length,0);assert.match($(c,'#result-count').textContent,/0 \/ 1 cards/);assert.equal(c.w.document.querySelectorAll('[data-drop-status]').length,6);click(c,'[data-action="reset-filters"]');assert.equal(c.w.document.querySelectorAll('[data-card]').length,1);});
await check('The parent iframe bridge saves PRD edits and editor history while preserving unknown fields',async()=>{const incoming=clone(c.w.dwdgPlanningBridge.getPrd());incoming.nodes[1].notes='Updated from the editor bridge';incoming.changeHistory={kind:'dwdg-one-prd-history',schemaVersion:1,scope:'dwdg-one-prd-planner:2026-10-03-v1',events:[]};delete incoming.nodes[1].externalTool;delete incoming.externalContext;c.w.dwdgPlanningBridge.updatePrd(incoming,'Edited HR requirement');await c.advance();assert.equal(c.stored.prd.nodes[1].notes,'Updated from the editor bridge');assert.deepEqual(c.stored.prd.nodes[1].externalTool,{label:'Keep'});assert.deepEqual(c.stored.prd.externalContext,{origin:'Other AI'});assert.deepEqual(c.stored.customMetadata,{tool:'Claude'});assert.equal(c.stored.prd.changeHistory.kind,'dwdg-one-prd-history');});
await check('Work Undo cannot silently revert a later PRD change from an older whole-document snapshot',async()=>{click(c,'[data-view="kanban"]');click(c,'[data-action="undo-work"]');await c.advance();assert.equal(c.stored.prd.nodes[1].notes,'Updated from the editor bridge');});
await check('Linked requirement chips select the real requirement editor through its public API',()=>{const frame=new Window({url:'http://127.0.0.1:5174/'});windows.push(frame);frame.TextEncoder=TextEncoder;frame.dwdgPrdBridge={getDocument:()=>c.w.dwdgPlanningBridge.getPrd(),onChange:(doc,summary)=>c.w.dwdgPlanningBridge.updatePrd(doc,summary)};const template=fs.readFileSync(new URL('./editor-shell.html',import.meta.url),'utf8').replace('__PRD_SEED__','[]');frame.document.body.innerHTML=template;frame.eval(template.match(/<script>\s*([\s\S]*?)<\/script>\s*$/)[1]);$(c,'#prd-frame').contentWindow.dwdgPrdEditor=frame.dwdgPrdEditor;c.w.dwdgPlanningBridge.editorReady();click(c,'[data-view="kanban"]');click(c,'[data-action="requirement"][data-id="hr"]');assert.equal($(c,'#view-title').textContent,'Requirements');assert.equal(frame.document.querySelector('[data-read]').hidden,false);assert.equal(frame.document.querySelector('[data-field="title"]').value,'HR monitoring');assert.equal(frame.dwdgPrdEditor.selectRequirement('missing-id'),false);assert.equal(frame.document.querySelector('[data-field="title"]').value,'HR monitoring');});
await check('Save completion never overwrites a newer edit made during an in-flight PUT',async()=>{const held=await start({holdFirst:true});click(held,'[data-view="kanban"]');status(held,'ready');await held.advance();assert.equal(held.requests.length,1);assert.ok(held.held);status(held,'doing');await held.advance();assert.equal(held.requests.length,1);held.held();await held.settle();assert.equal($(held,'[data-move-card="card"]').value,'doing');await held.advance(100);assert.equal(held.requests.length,2);assert.equal(held.requests[1].document.cards[0].status,'doing');assert.equal(held.requests[1].baseEtag,'etag-1');assert.equal(held.stored.cards[0].status,'doing');});
await check('A stale 409 pauses autosave and Retry cannot overwrite the external revision',async()=>{const conflict=await start({conflict:true});click(conflict,'[data-view="kanban"]');status(conflict,'ready');await conflict.advance();assert.equal(conflict.requests.length,1);assert.match($(conflict,'#save-status').textContent,/File changed elsewhere/);click(conflict,'[data-action="retry"]');status(conflict,'doing');await conflict.advance(1000);assert.equal(conflict.requests.length,1);assert.equal($(conflict,'[data-move-card="card"]').value,'doing');assert.equal(conflict.stored.cards[0].status,'backlog');});
await check('Import review rejects malformed JSON and broken requirement links before applying',async()=>{click(c,'[data-action="import"]');$(c,'#import-text').value='{broken';click(c,'[data-action="validate-import"]');await c.settle();assert.equal($(c,'[data-action="apply-import"]').disabled,true);const broken=c.stored;broken.prd.nodes=broken.prd.nodes.filter(n=>n.id!=='hr');$(c,'#import-text').value=JSON.stringify(broken);click(c,'[data-action="validate-import"]');await c.settle();assert.equal($(c,'[data-action="apply-import"]').disabled,true);assert.match($(c,'#import-result').textContent,/linked requirements|missing ID hr/);assert.equal(c.stored.prd.nodes.length,2);});
await check('Import review rejects duplicate IDs and broken story relationships using complete validation',async()=>{const duplicate=c.stored;duplicate.cards.push(clone(duplicate.cards[0]));$(c,'#import-text').value=JSON.stringify(duplicate);click(c,'[data-action="validate-import"]');await c.settle();assert.equal($(c,'[data-action="apply-import"]').disabled,true);assert.match($(c,'#import-result').textContent,/duplicate ID/);const broken=c.stored;broken.stories[0].activityId='missing-activity';$(c,'#import-text').value=JSON.stringify(broken);click(c,'[data-action="validate-import"]');await c.settle();assert.equal($(c,'[data-action="apply-import"]').disabled,true);assert.match($(c,'#import-result').textContent,/missing ID missing-activity/);assert.equal(c.stored.stories[0].activityId,'monitor');});
await check('Reviewed valid imports remain explicit and preserve existing work links',async()=>{const valid=c.stored;valid.notes='Reviewed import from another AI';$(c,'#import-text').value=JSON.stringify(valid);click(c,'[data-action="validate-import"]');await c.settle();assert.equal($(c,'[data-action="apply-import"]').disabled,false);assert.notEqual(c.stored.notes,valid.notes);click(c,'[data-action="apply-import"]');await c.advance();assert.equal(c.stored.notes,'Reviewed import from another AI');assert.equal(c.stored.cards[0].storyIds[0],'story');});
await check('An older polling GET cannot replace a file revision saved while that GET was in flight',async()=>{const ctx=await start({holdPoll:true});click(ctx,'[data-view="kanban"]');ctx.poll();await ctx.settle();assert.ok(ctx.heldPoll);status(ctx,'ready');await ctx.advance();assert.equal(ctx.stored.cards[0].status,'ready');ctx.heldPoll();await ctx.settle();assert.equal($(ctx,'[data-move-card="card"]').value,'ready');assert.match($(ctx,'#revision-label').textContent,/Revision 1/);});
for(const window of windows)await window.happyDOM.abort();
console.log(checks+' planning UI checks passed. File/HTTP operations are tested separately in planner-store.test.mjs.');
