import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const dir=path.dirname(fileURLToPath(import.meta.url));
const files=['sections-foundation.json','sections-detail.json','sections-product.json'];
const sources=new Map(files.map(file=>[file,JSON.parse(fs.readFileSync(path.join(dir,file),'utf8'))]));
const model=new Map([...sources.values()].flat().map(n=>[n.id,n]));
const deps={
 'vision-personas':['access_action_matrix','org_current_six'],
 'vision-capacity-fixtures':['vision-capacity','scope_student_scale'],
 'vision-pilot-value':['vision-pains','analytics_metric_policy'],
 'vision-distribution':['org_identity','access_action_matrix'],
 'design-shell':['org_vocabulary','access_surface_scope'],
 'design-navigation':['design-shell','org_vocabulary'],
 'design-project-tabs':['work_project_tabs','work_task_fields','resource_types'],
 'design-density':['design-reference'],
 'design-materials':['design-reference'],
 'design-typography':['design-reference'],
 'design-actions':['work_forms','work_concurrent_updates'],
 'design-inspector':['resource_inspector','resource_tasks'],
 'design-overlays':['engineering-drafts'],
 'design-motion':['design-reference'],
 'design-languages':['vision-name'],
 'design-time':['org_timezone_calendar'],
 'design-empty':['engineering-errors'],
 'design-search':['work_search'],
 'design-mobile':['design-navigation'],
 'design-preferences':['work_settings'],
 'design-ui-review':['design-density','design-typography','design-languages','design-accessibility'],
 'quality-role-matrix':['access_action_matrix','security_permissions','security_offboarding'],
 'quality-journey-matrix':['user-flows','work_task_lifecycle','resource_types'],
 'quality-integrity':['data_validation','data_concurrency','data_softdelete'],
 'quality-regression':['work_concurrent_updates','engineering-record-removal'],
 'quality-visual':['measure-design-handoff','design-ui-review'],
 'quality-performance':['reliability_performance'],
 'quality-security-review':['security_tests'],
 'quality-backup-proof':['reliability_restore'],
 'quality-notification-proof':['work_reminders','work_updates'],
 'quality-feedback':['onboarding-help'],
 'quality-observability':['reliability_monitoring','reliability_logs'],
 'roadmap-plan':['scope_rules_gap','decision-file-policy','decision-invite','strategy_validation','hr_validation','finance_sop'],
 'roadmap-foundation':['roadmap-plan','engineering-modules','security_auth','data_identity'],
 'roadmap-core':['roadmap-foundation','user-flows','work_project_tabs','access_surface_scope'],
 'roadmap-isolated':['roadmap-core','reliability_restore','security_tests','environments_sandbox'],
 'roadmap-pilot':['roadmap-isolated','launch_gate'],
 'roadmap-rollout':['roadmap-pilot','launch_datacutover','launch_onboarding'],
 'roadmap-maintenance':['reliability_monitoring','org_handover'],
 'decision-free-tradeoff':['costs_monthlyA','costs_owner','reliability_freepause'],
 'decision-file-policy':['scope_org_storage_setup','resource_provider_access'],
 'decision-invite':['access_action_matrix','org_batch_model'],
 'decision-sop':['scope_hr_strategy_gap','strategy_validation','hr_validation','finance_sop','consulting_validation','marketing_validation','external_validation'],
 'decision-reminders':['scope_student_scale','work_updates'],
 'decision-data-policy':['security_privacy'],
 'decision-brand':['vision-name','design-reference'],
 'decision-pilot':['quality-defects','vision-capacity-fixtures'],
 'decision-restructure':['org_future_three_vp','org_activation_preview'],
 'prd-management-baseline':['prd-management-status','prd-management-dependencies'],
 'onboarding-first-admin':['access_admin_scope','security_bootstrap','reliability_succession'],
 'onboarding-invitations':['access_invitation','security_auth'],
 'onboarding-first-view':['access_surface_scope','design-shell'],
 'onboarding-quick-guide':['design-navigation','work_task_lifecycle','resource_provider_access'],
 'onboarding-migration':['data_legacy','data_manifest'],
 'onboarding-profile':['data_people','security_privacy'],
 'onboarding-switcher':['access_project_collab','access_revocation'],
 'onboarding-leavers':['security_offboarding','access_revocation','data_people'],
 'onboarding-help':['reliability_support','reliability_outage'],
 'integration-links':['resource_link_validation','security_web'],
 'integration-provider-access':['resource_provider_access','access_url_disclosure'],
 'integration-previews':['integration-links','integration-provider-access'],
 'integration-drive-ownership':['scope_org_storage_setup','resource_provider_access'],
 'integration-auth':['security_auth','access_invitation','infrastructure_accounts'],
 'integration-email':['decision-reminders','costs_email'],
 'integration-calendar':['work_schedule','org_timezone_calendar'],
 'integration-whatsapp':['scope_deferred'],
 'integration-credentials':['resource_secret_links','security_secrets'],
 'integration-signature':['legal_signature_status','access_legal_policy'],
 'integration-payments':['finance_validation','access_finance_policy'],
 'integration-ai':['scope_optional_services','security_exports'],
 'integration-exports':['data_json','data_csv','resource_export_security'],
 'engineering-modules':['org_workspace_config','data_identity'],
 'engineering-capability-registry':['org_workspace_config','org_capability_owner'],
 'engineering-api':['data_validation','security_permissions'],
 'engineering-transactions':['data_concurrency','security_audit'],
 'engineering-state':['data_identity','engineering-api'],
 'engineering-errors':['security_web','data_concurrency'],
 'engineering-drafts':['data_concurrency','security_device'],
 'engineering-versioning':['data_json','releases'],
 'engineering-review':['environments_test','quality-defects'],
 'engineering-dependencies':['security_vendor'],
 'engineering-assets':['design-reference'],
 'engineering-routing':['access_surface_scope','work_link_integrity'],
 'engineering-time-tests':['data_dates','data_money'],
 'engineering-kpi-contract':['analytics_metric_policy','analytics_progress','analytics_average'],
 'engineering-record-removal':['data_softdelete','access_action_matrix','data_concurrency'],
 'design-resource-identity':['resource_types','resource_link_validation'],
 'design-shaders':['measure-motion','quality-performance'],
 'design-discoverability':['design-navigation','resource_inspector'],
 'design-availability-evidence':['availability_declared','availability_overlap'],
 'design-availability-assignment':['availability_capacity','availability_override'],
 'design-timeline-interactions':['timeline_date_validation','timeline_accessible'],
 'design-collaboration-editing':['resource_notes','work_concurrent_updates'],
 'org_workspace_config':['org_team_identity','access_action_matrix'],
 'org_other_orgs':['org_identity'],
 'org_timezone_calendar':[],
 'access_admin_scope':['org_current_six'],
 'access_vp_scope':['org_reporting_graph','access_action_matrix'],
 'access_invitation':['access_current_leaders','access_action_matrix'],
 'access_revocation':['access_surface_scope'],
 'access_delegation':['access_project_collab','access_action_matrix'],
 'work_task_fields':['org_timezone_calendar','access_action_matrix'],
 'work_forms':['work_task_fields','access_surface_scope'],
 'work_projects_register':['access_surface_scope','org_timezone_calendar'],
 'work_task_lifecycle':['work_task_fields','access_member_edit'],
 'work_milestones':['work_overview','access_project_roles'],
 'work_schedule':['work_task_fields','org_timezone_calendar'],
 'work_updates':['access_surface_scope','access_revocation'],
 'work_reminders':['work_updates','org_timezone_calendar'],
 'division_hr':['org_current_six'],
 'division_external':['org_current_six'],
 'division_marketing':['org_current_six'],
 'division_legal_finance':['org_current_six'],
 'division_consulting':['org_current_six'],
 'strategy_validation':['org_current_six'],
 'hr_validation':['org_current_six','access_sensitive_data'],
 'external_relationship':['access_sensitive_data'],
 'marketing_campaign':['access_action_matrix','org_timezone_calendar'],
 'marketing_validation':['access_action_matrix','resource_provider_access'],
 'finance_sop':['access_finance_policy'],
 'consulting_validation':['access_project_roles'],
 'resource_types':['org_vocabulary','access_surface_scope'],
 'resource_creator':['access_surface_scope'],
 'resource_provider_access':['access_action_matrix'],
 'resource_secret_links':['access_sensitive_data','security_secrets'],
 'resource_launch_limits':['scope_student_scale','scope_org_storage_setup'],
 'resource_notes':['work_forms','resource_types'],
 'resource_folder':['resource_types','access_surface_scope'],
 'resource_link_validation':['resource_types','security_web'],
 'resource_pin':['access_surface_scope','resource_types'],
 'analytics_metric_policy':['vision-pains','scope_student_scale'],
 'scope_rules_gap':['access_current_leaders','access_review_self_policy','security_privacy'],
 'scope_pilot':['access_action_matrix','quality-defects'],
 'scope_links_default':['scope_org_storage_setup','resource_types'],
 'survey_consulting_qualitative':[],
 'survey_legal_qualitative':[],
 'survey_marketing_qualitative':[],
 'survey_external_qualitative':[],
 'survey_secret_search':[]
};
for(const [id,values] of Object.entries(deps)){if(!model.has(id))throw new Error('Unknown root-owned requirement '+id);model.get(id).dependencies=[...new Set(values)].join('\n');}
const criteria={
 'root':['Every current requirement ID can be inspected/edited; add/move/delete is recoverable through Undo.','Portable export includes N requirements for an N-node chosen document, with 0 silently dropped IDs or fields.','Budget remains Rp35,000/month target and Rp50,000/month hard ceiling; roughly40+ members is approximate, not an audited count.'],
 'vision-name':['Exactly1 product term Workspace refers to organizational context; project main navigation has exactly3 tabs Overview / Work / Resources.','Core navigation/forms/help use the adopted EN/ID vocabulary in100% of reviewed instances.'],
 'vision-personas':['Map member, lead, VP, President, admin and specialist reviewer to at least6 explicit actor/action/scope fixture categories.','Each adopted journey identifies1 accountable policy owner and a denied/recovery path;0 title-only unlimited authority grants.'],
 'vision-capacity':['Count actual invited/active members before pilot; record1 dated approximate→verified roster decision.','Do not equate the40+ estimate to a measured concurrency or guaranteed hosting capacity.'],
 'vision-pilot-value':['At least1 representative from each of6 current divisions completes an observed minimum journey.','In a resource-finding exercise, proposed target is≤60s per required known resource; record per-person time and sample size rather than claim a measured result.','Collect0 private HR/finance bodies for adoption analytics and produce0 member productivity rankings.'],
 'vision-distribution':['Unauthenticated fixture has0 internal record/title/count disclosures.','A foreign organization ID has0 allowed DWDG reads/writes/search/export results.'],
 'design-shell':['Switch across Home/Projects/Resources for all6 division fixtures; exactly1 persistent shell and1 meaningful workspace context remain.','Every allowed/denied workspace option reconciles with the action/scope matrix;0 duplicate division navigation.','Geometry follows measure-shell (216px sidebar/56px toolbar/40px navigation baseline).'],
 'design-navigation':['Each project has exactly3 primary tabs, with view choices inside the adopted tab.','At320px and200% text zoom,0 required actions are available only by hover.'],
 'design-project-tabs':['Create1 task from1 resource; the same task ID appears in Work, relevant Overview counts and timeline without a duplicate.','Exactly3 primary tabs remain; activity is contextual unless a separate later decision is recorded.'],
 'design-density':['At1440×900 normal zoom, first ordinary project row top≤450px and≥4 complete76px rows are visible.','At200% text zoom, content can expand;0 essential title/action clipping is caused by fixed row heights.'],
 'design-typography':['Computed baseline matches measure-type-desktop and measure-type-mobile; operational product text≥12px.','Ten fixture date/count/IDR rows align; font failure preserves100% of essential labels/actions.'],
 'design-actions':['For every adopted primary action, test success, denied, validation, conflict and failure:5 outcomes with0 false-success messages.','Each committed record mutation produces1 coherent history operation and persists after reload.'],
 'design-inspector':['For6 resource-kind fixtures, pointer, keyboard and touch routes open the same stable ID and permitted action set.','After10 open/close cycles, origin scroll/selection and uncommitted draft remain intact.'],
 'design-overlays':['Test4 viewport corners, Escape, nested menu, deleted opener and unsaved draft navigation.','0 focus escapes from a modal;1 live opener receives focus on return where it still exists.','Adopted gap/dimensions follow measure-dialogs and measure-popovers.'],
 'design-languages':['Review2 languages ×2 themes on all adopted shared controls;0 missing translation keys or raw internal error strings.','User content is translated automatically0 times.'],
 'design-time':['A date-only deadline remains1 all-day calendar date in Asia/Jakarta, with0 invented meeting hour.','A timed meeting retains the exact start/end instants across2 device timezones and date-boundary fixtures.'],
 'design-empty':['Exercise5 distinct states(empty/loading/denied/offline/failed) with0 fabricated records/charts and0 erased drafts.','Each actionable failure has1 understandable retry/resolve path where applicable.'],
 'design-search':['Search fixtures include task/project/resource and protected HR/finance fields;0 unauthorized matches/counts appear.','Revoke1 membership while a result is open: subsequent detail/read/write rechecks permission and exposes0 formerly allowed content.'],
 'design-mobile':['At320/390px, ordinary form/page scroll width equals available viewport width;0 essential actions are clipped.','Complete at least1 Android and1 iOS real-device task/resource/review journey before product acceptance.','Primary touch targets≥44×44px under adopted measure-targets.'],
 'design-accessibility':['Core keyboard journeys have0 inaccessible actions or invisible focus states.','Apply WCAG2.2AA target/contrast/reflow tests in measure-targets,measure-contrast andmeasure-focus-zoom.','Automated/manual findings list expected/observed evidence;0 certification claims are inferred from a test score.'],
 'design-preferences':['Change language/theme/time preference once; it applies to all permitted screens for that user and does not alter another fixture user.','Logout/shared-device fixture retains0 private record caches under the adopted device policy.'],
 'design-ui-review':['Review5 widths ×2 languages ×2 themes=20 configurations for representative core screens and6 minimum division journeys.','0 unresolved essential layout/focus/action defects remain; record source IDs and measured exceptions.'],
 'quality-journey-matrix':['Execute1 member journey,1 lead journey,1 resource/task journey,1 meeting journey and at least1 per6 division paths.','For every executed flow, record actor, input, saved IDs, permitted output, denied/failure route and reload/export result.'],
 'quality-visual':['Review20 width/language/theme combinations defined bymeasure-design-handoff for core representative screens.','0 clipped essential controls, overlapping labels, false chart data or inaccessible focus states remain.'],
 'quality-notification-proof':['An overdue fixture created while logged out appears exactly1 time in the correct in-app due context after return.','Retry a queued action3 times:0 duplicate recipient notifications or unauthorized payloads.','Optional closed-app channels get separate executed evidence only if adopted.'],
 'quality-defects':['General launch has0 unresolved P0/P1 defects in promised essential scope.','100% of known P2 issues have owner, user impact and workaround/plan.','Candidate sign-off records1 exact build/PRD version, tested scope and explicit feature exclusions.'],
 'prd-management-editor':['Add/edit/move/delete1 temporary subtree; Undo restores its exact stable IDs and field values.','For N current requirements, JSON/Markdown export containsN IDs; importing a valid chosen copy discards0 history events silently.','Current app data is changed0 times by planning edits.'],
 'onboarding-invitations':['Test5 cases(expired/revoked/duplicate/wrong-email/already-member):0 unauthorized or duplicate memberships.','A successful acceptance binds exactly1 verified identity to the approved membership; delivery failure does not create fake acceptance.'],
 'onboarding-first-view':['Member/lead/VP/President/admin fixtures land in allowed contexts only;0 internal content appears outside permitted scope.','Empty fixtures offer at least1 appropriate permitted next action or clear help path.'],
 'onboarding-profile':['A member can complete1 assigned task with0 uploaded photos and0 mandatory unneeded home/DOB/student-ID data.','Editing1 ordinary profile field grants0 extra role/approval permissions.'],
 'onboarding-switcher':['Move1 member fromA toB and add/revoke1 project-only exception; current permitted IDs reconcile exactly.','After revocation,0 direct API/search/history/export payloads from former scope remain available to new actions.'],
 'onboarding-leavers':['Suspend1 active fixture identity; subsequent protected reads/writes/export execution return0 allowed data.','Reassign its outstanding work through1 reviewed mapping, preserving100% of historical stable author IDs.'],
 'integration-links':['Test HTTPS,missing URL,malformed URL,javascript:,data: andfile: fixtures;0 unsafe URL executions.','For valid links, app metadata records1 owner/custodian and never claims to have granted provider access.'],
 'integration-provider-access':['Assign1 person to1 provider link; provider permissions change0 times automatically.','A denied external file has1 visible access-request/owner route; app assignment shows0 false open-access promises.'],
 'integration-exports':['Export known20-record relation fixture with exact counts and0 unauthorized fields.','Formula-like CSV values remain inert; portable JSON restores stable IDs and relationship counts exactly.'],
 'engineering-transactions':['Inject1 failure between data update and history write:0 partial committed records or fake successful events.','Retry the same command3 times:exactly1 committed logical change set.'],
 'engineering-state':['Change1 task from list/board/timeline:exactly1 stable task record changes and3 permitted views reconcile.','Reload/export retain100% of fixture IDs/relations, with0 view-specific shadow copies.'],
 'engineering-drafts':['Inject failed/offline/conflict outcomes on3 draft saves:0 typed-text loss and0 premature Saved labels.','Success appears only after authoritative acknowledgement; rejected writes preserve1 recoverable draft.'],
 'engineering-time-tests':['Execute before-midnight/after-midnight,date-only,timed-end and cancelled-event cases with exact intended Asia/Jakarta outcomes.','Finance fixtures use integer IDR and0 float rounding drift in allocation/payment reconciliation.'],
 'engineering-record-removal':['Delete1 permitted3-record hierarchy through preview;0 hidden restricted child metadata is disclosed.','Where restoration is permitted, restore all3 stable IDs/relations without overwriting1 later conflicting change.','Permanent purge occurs only under the adopted retention/authorization process.'],
 'access_action_matrix':['The adopted matrix covers read/create/update/assign/review/approve/archive/restore/export/manage_members/manage_roles for every adopted object family.','All tested actor/action/scope cells produce expected allow/deny;0 undefined default-allow cells.','Member,lead,VP,President,admin and independent-review fixtures include at least6 role categories.'],
 'access_surface_scope':['Navigation/search/counts/charts/resource/history/export share the same allowed-record fixture IDs.','ForA-only/B-only/revoked/explicit-project-collaborator fixtures,0 unauthorized IDs,fields or counts leak.'],
 'access_member_scope':['A normal1-division member can see exactly its permitted workspace and0 other full division workspaces.','Any adopted cross-division project exception exposes only its explicitly allowed records, not an extra full workspace.'],
 'access_vp_scope':['For eachVP fixture, allowed workspace IDs equal its effective reporting descendants exactly.','A reporting change invalidates0 unrelated work records and grants0 unrelated divisions.'],
 'work_task_fields':['Create4 tasks(undated,date-only,timed,unassigned queue); all4 stable IDs persist with correct field/null semantics.','There are0 fabricated completion timestamps,implicit meeting hours or duplicate assignee links.'],
 'work_task_lifecycle':['Move1 task through each adopted transition and back through permitted review/reopen; each change has1 authoritative event.','Reject1 invalid transition and1 unauthorized transition with0 record changes.','Completing/reopening1 task changes actual current state/history truth without fabricating previous dates.'],
 'work_work_views':['With30 task fixtures, list/board/timeline contain the same30 unique IDs under the same filter.','Edit1 task in each view; exactly1 record changes per operation and the other2 views reconcile.'],
 'work_forms':['Submit3 invalid fields:0 invalid committed records,3 associated errors and100% retained draft values.','Test1 timeout retry,1 conflict and1 denied operation with0 silent overwrite or false success.'],
 'work_project_tabs':['Each project has exactly3 primary tabs Overview/Work/Resources.','1 linked task/resource appears through the same stable IDs in all relevant views, with0 duplication.'],
 'work_concurrent_updates':['Two authorized users edit1 task from the same version; incompatible changes produce1 explicit recoverable conflict or adopted safe merge.','There are0 silent lost accepted writes or unauthorized conflict resolutions.'],
 'work_meeting_outcomes':['One meeting creates2 linked follow-up tasks and1 decision from its minutes using canonical IDs.','The meeting/project/resource views reconcile those3 outputs exactly after reload/export.'],
 'work_undo_archive':['For1 acknowledged change, permitted Undo retains the original event and appends1 reversal event.','If another user made1 incompatible later change, Undo changes0 fields until conflict/permission review succeeds.'],
 'work_reminders':['One due fixture has1 intended recipient rule and no delivery to unauthorized members.','Retry3 times produces0 duplicate logical notifications; quiet-hours/opt-out cases retain correct in-app due work.','App copy promises0 unconfigured closed-app or WhatsApp delivery.'],
 'external_relationship':['One relationship links2 projects and retains exactly1 accountable PIC plus the recorded next action.','0 contacts are exposed outside the adopted contact-field policy.'],
 'marketing_campaign':['One campaign locates3 linked content items and2 asset references without duplicating their canonical IDs.','Engagement values are invented0 times; absent actual metrics remain unavailable.'],
 'resource_types':['Render6 launch-kind fixtures; each distinguishes native note/folder/provider URL/template/meeting context appropriately.','Native binary upload controls are available0 times by default.'],
 'resource_folder':['Create1 three-level folder hierarchy;0 cycles,self-parent links or foreign-workspace children are accepted.','Rename/move1 folder preserves100% of fixture resource IDs and explicit relationships.'],
 'resource_notes':['A 1,000-word note is editable/findable/exportable; inject1 failed save and retain100% of typed text.','Successful revision acknowledgement persists after1 reload; unacknowledged text shows0 false Saved states.'],
 'resource_tasks':['Create1 task from1 resource and delegate to1 eligible person; exactly1 task ID and1 association are created.','Retry3 times creates0 duplicate task/resource associations.'],
 'resource_provider_access':['Adding1 DWDG responsibility assignment changes external provider permissions0 times.','Broken or denied provider links retain1 identifiable custodian/recovery route.'],
 'resource_secret_links':['Search/export1 fixture vault reference and1 forbidden secret marker; marker occurrences in user-facing results/history/export equal0.','Account discovery returns owner and approved access path only;0 plaintext tokens/passwords are stored.'],
 'analytics_progress':['Fixture10 eligible flat tasks with4 completed gives exactly40% current progress.','If optional subtasks are adopted, parent groups contribute0 extra counted units and only adopted eligible leaves determine numerator/denominator.','Zero-task denominator displays unavailable/empty rather than a fabricated score.'],
 'analytics_completion':['Only actual saved completion timestamps enter historical bins; undated completed fixtures contribute0 invented dated observations.','Reopen1 task preserves historical event truth while current-state totals change accurately.'],
 'analytics_average':['Fixture3 observed finished days with counts0,2,4 yields average2; today,future andunobserved days contribute0 denominator units.','The displayed basis/timezone/date interval is explicit for100% of this report.']
};
for(const [id,checks] of Object.entries(criteria)){if(!model.has(id))throw new Error('Unknown acceptance target '+id);model.get(id).acceptance=checks.map((check,i)=>`${i+1}. ${check}`).join('\n');}
const root=model.get('root');root.notes=root.notes.replace('draft 0.1','draft 0.2');
model.get('scope').notes='P0 means launch integrity or a complete minimum daily journey. P1 is important in the explicitly adopted scope; a P1 requirement may be deferred with a documented exclusion, while a P1 defect in promised essential behavior cannot be excused. P2 remains optional/later. A dense PRD can capture future direction without treating all brainstorms as a first-release commitment.';
model.get('prd-management-editor').notes+='\nRevision0.2 adds a continuous All nodes list and entire-document map option. Older baseline0.1 is preserved separately; browser changes are not implicitly merged into a regenerated seed.';
// Preserve meaningful original checks while consistently numbering unstructured acceptance fields.
for(const nodes of sources.values())for(const n of nodes){if(typeof n.acceptance==='string'&&!/^\s*\d+[.)]\s/.test(n.acceptance))n.acceptance='1. '+n.acceptance;}
for(const [file,nodes] of sources)fs.writeFileSync(path.join(dir,file),JSON.stringify(nodes,null,2)+'\n');
console.log(JSON.stringify({rootOwnedNodes:model.size,dependencyContracts:Object.keys(deps).length,substantiveAcceptanceRevisions:Object.keys(criteria).length}));
