document.querySelector('h1').textContent='Welcome back, Mahdy';
document.querySelector('.heading p').textContent='Here’s what’s happening across DWDG UII.';
document.querySelector('footer span:last-child').textContent='Design concept / 02';
const captions=[['6 divisions','Organization-wide'],['Assigned to you','Your priorities'],['Blocked tasks','Review needed'],['Completed tasks','This week']];
document.querySelectorAll('.metric').forEach((m,i)=>{const inner=document.createElement('div');inner.className='metric-inner';while(m.firstChild)inner.append(m.firstChild);inner.insertAdjacentHTML('beforeend','<div class="spark" aria-hidden="true">'+[15,26,20,34,24,29].map(h=>`<i style="height:${h}px"></i>`).join('')+'</div>');m.append(inner);m.insertAdjacentHTML('beforeend',`<div class="metric-caption"><span>${captions[i][0]}</span><b>${captions[i][1]}</b></div>`)});
const analytics=document.createElement('section');analytics.className='analytics';analytics.setAttribute('aria-label','Sample organization activity');analytics.innerHTML=`<section class="chart-shell"><div class="shell-heading"><span>WORK COMPLETED</span><span>Sample organization data</span></div><div class="chart-inner"><div class="chart-top"><div><div class="chart-number"><span id="chart-total">0</span><small>tasks completed</small></div><div class="chart-sub" id="chart-period">September · Across all divisions</div></div><div class="segments" aria-label="Chart period"><button data-period="week">Week</button><button class="active" data-period="month">Month</button></div></div><div class="pixel-chart" id="pixel-chart" aria-label="Tasks completed each day"></div><div class="chart-labels" id="chart-labels"></div><div class="chart-insight" id="chart-insight"></div></div></section><section class="chart-shell"><div class="shell-heading"><span>DIVISION WORKLOAD</span><span>Open tasks</span></div><div class="chart-inner"><div class="chart-top"><div><div class="chart-number">36<small>tasks in progress</small></div><div class="chart-sub">Shared effort. Visible progress.</div></div></div><div class="breakdown" role="img" aria-label="Open tasks by division: Consulting 9, Strategy and Growth 5, Human Resource 7, Client Engagement 4, Marketing Communication and IT 8, Legal and Finance 3. Completed tasks respectively: 7, 8, 5, 6, 6, 4.">${[[9,7],[5,8],[7,5],[4,6],[8,6],[3,4]].map(([a,b])=>`<div class="bar-group"><i style="height:${a*11}px"></i><i style="height:${b*11}px"></i></div>`).join('')}</div><div class="chart-labels"><span>CON</span><span>S&G</span><span>HR</span><span>CE</span><span>MCIT</span><span>L&F</span></div><div class="legend"><span>In progress</span><span>Completed</span></div></div></section>`;
document.querySelector('.metrics').after(analytics);
const tooltip=document.createElement('div');tooltip.className='chart-tooltip hidden';tooltip.setAttribute('role','status');document.body.append(tooltip);
const daily=[3,4,6,5,8,3,2,4,7,9,6,5,3,2,5,8,6,10,7,4,6,9,8,5,4,6,8,7,9,11];
function drawChart(period){const values=period==='week'?daily.slice(14,21):daily;const start=period==='week'?15:1;document.querySelector('#chart-total').textContent=values.reduce((a,b)=>a+b,0);document.querySelector('#chart-period').textContent=period==='week'?'15–21 September · Across all divisions':'September · Across all divisions';document.querySelector('#chart-labels').innerHTML=(period==='week'?['15 Sep','16','17','18','19','20','21 Sep']:['01 Sep','05','10','15','20','25','30 Sep']).map(x=>`<span>${x}</span>`).join('');document.querySelector('#chart-insight').innerHTML='<b>Select a column</b> to see the daily total. All figures are illustrative.';const plot=document.querySelector('#pixel-chart');plot.innerHTML=values.map((value,i)=>`<button class="pixel-col" aria-label="September ${start+i}: ${value} tasks completed" data-chart-day="${start+i}" data-value="${value}">${Array.from({length:12},(_,j)=>`<i class="${j<value?'filled':''}"></i>`).join('')}</button>`).join('');plot.querySelectorAll('button').forEach(b=>{const reveal=()=>{const r=b.getBoundingClientRect();tooltip.innerHTML=`September ${b.dataset.chartDay}<b>${b.dataset.value} tasks completed</b>`;tooltip.style.left=Math.min(window.innerWidth-190,Math.max(10,r.left-45))+'px';tooltip.style.top=Math.max(10,r.top-74)+'px';tooltip.classList.remove('hidden')};b.onmouseenter=reveal;b.onfocus=reveal;b.onmouseleave=()=>tooltip.classList.add('hidden');b.onblur=()=>tooltip.classList.add('hidden');b.onclick=()=>{document.querySelector('#chart-insight').textContent=`September ${b.dataset.chartDay} · ${b.dataset.value} tasks completed across all divisions (sample data).`;reveal()}});document.querySelectorAll('[data-period]').forEach(b=>{b.classList.toggle('active',b.dataset.period===period);b.setAttribute('aria-pressed',String(b.dataset.period===period))})}
document.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>drawChart(b.dataset.period));drawChart('month');
const dock=document.createElement('nav');dock.className='mobile-dock';dock.setAttribute('aria-label','Mobile navigation');dock.innerHTML='<button aria-label="Overview"><i data-icon="grid"></i>Home</button><button aria-label="My tasks"><i data-icon="check"></i>Tasks</button><button aria-label="Calendar"><i data-icon="calendar"></i>Schedule</button><button aria-label="Create task"><i data-icon="plus"></i>Create</button>';document.body.append(dock);dock.children[0].onclick=()=>window.scrollTo({top:0});dock.children[1].onclick=()=>document.querySelector('#tasks-panel').scrollIntoView({block:'start'});dock.children[2].onclick=()=>document.querySelector('.days').scrollIntoView({block:'center'});dock.children[3].onclick=()=>document.querySelector('#newtask').click();icons();

window.addEventListener("resize",()=>tooltip.classList.add("hidden"));
window.addEventListener("scroll",()=>tooltip.classList.add("hidden"),{passive:true});
