import {mountPrism} from './v03-materials.mjs';
import {createBackend, DIVISION_CODES, previewLegacyBackup} from './shared-backend.mjs';
import {makeDivisionSeed,makeDivisionDemoData,validateDivisionState,mountDivisionWorkspace} from './division-workspaces.mjs';
import {mountProjectExtras} from './project-extras.mjs';
import {DIVISIONS,STATUSES,STORE_KEY,iso,day,addDays,diffDays,uid,makeSeed,progress,taskError,projectError,eventError,applyTask,shiftTask,deleteTask,validateState} from './model.mjs';
const $=s=>document.querySelector(s);
const h=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={home:'M3 10l9-7 9 7v11H3z M9 21v-8h6v8',projects:'M3 7h18v14H3z M8 7V3h8v4 M3 12q9 5 18 0 M12 12v4',tasks:'M9 11l3 3L22 4 M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11',calendar:'M4 5h16v16H4z M4 10h16 M8 3v4 M16 3v4',gantt:'M3 4v17h18 M6 7h6 M10 11h8 M14 15h7',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M12 2v3 M12 19v3 M2 12h3 M19 12h3 M5 5l2 2 M17 17l2 2 M5 19l2-2 M17 7l2-2',plus:'M12 5v14 M5 12h14',arrow:'M7 17L17 7 M7 7h10v10',chevron:'M9 5l7 7-7 7',left:'M15 5l-7 7 7 7',close:'M6 6l12 12 M6 18L18 6',people:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8 M18 8a3 3 0 0 1 0 6 M22 21v-2a4 4 0 0 0-3-4',globe:'M21 12a9 9 0 1 0-18 0 9 9 0 0 0 18 0 M3 12h18 M12 3q-8 9 0 18 M12 3q8 9 0 18',flag:'M5 22V3 M5 3c5-4 9 4 15 0v11c-6 4-10-4-15 0',download:'M12 3v12 M7 10l5 5 5-5 M4 16v5h16v-5',upload:'M12 16V4 M7 9l5-5 5 5 M4 16v5h16v-5',menu:'M4 6h16 M4 12h16 M4 18h16',clock:'M21 12a9 9 0 1 0-18 0 9 9 0 0 0 18 0 M12 7v5l3 2',edit:'M15 4l5 5 M4 16L17 3l4 4L8 20l-5 1z',trash:'M4 6h16 M9 6V3h6v3 M6 6l1 15h10l1-15',link:'M10 14l4-4 M9 16l-2 2a4 4 0 0 1-6-6l5-5a4 4 0 0 1 6 0 M15 8l2-2a4 4 0 0 1 6 6l-5 5a4 4 0 0 1-6 0',check:'M5 12l4 4L19 6'};
const icon=(name,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.projects}"/></svg>`;
const today=()=>iso();
const fmt=(d,opts={day:'numeric',month:'short'})=>d?day(d).toLocaleDateString('en-GB',opts):'No date';
const fullDate=d=>fmt(d,{weekday:'long',day:'numeric',month:'long',year:'numeric'});
const initials=name=>name.trim().split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase();
const divisionRoutes=[['strategy-growth','Strategy & Growth','gantt'],['human-resource','Human Resource','people'],['external-engagement','External Engagement','globe'],['marketing-comms-it','Marketing, Communication & IT','calendar'],['legal-finance','Legal & Finance','projects'],['consulting','Consulting','tasks']];
const divisionNames=Object.fromEntries(divisionRoutes.map(([slug,name])=>[slug,name]));
const DIVISION_STORE_KEY='dwdg-division-preview-v03';
const runtimeEnv=import.meta.env||{};
const backendConfig=window.DWDG_BACKEND_CONFIG||{url:runtimeEnv.VITE_SUPABASE_URL,publishableKey:runtimeEnv.VITE_SUPABASE_PUBLISHABLE_KEY};
const sharedConfigured=!!(backendConfig.url&&backendConfig.publishableKey);
let sharedBackend=null,sessionInfo=null,authReady=!sharedConfigured,appError='',storageIssue='',rawBackup='',state,divisionData,unsubscribeShared=()=>{},unsubscribeAuth=()=>{},remoteRefreshTimer=0,pendingRemote=false,invitations=[],accessRoster={profiles:[],memberships:[],approvers:[]},notifications=[],projectCatalog=[],accessProjectId='',projectAccess=[];
if(sharedConfigured){state=makeSeed();divisionData=makeDivisionSeed(today());}
else{
  try{const raw=localStorage.getItem(STORE_KEY);if(raw){rawBackup=raw;state=JSON.parse(raw);if(!validateState(state))throw new Error('Invalid saved data');}else{state=makeSeed();localStorage.setItem(STORE_KEY,JSON.stringify(state));}}catch(e){state=makeSeed();storageIssue='Saved data could not be read. Export a backup in Workspace before replacing it; this preview is running in memory.';}
  try{const raw=localStorage.getItem(DIVISION_STORE_KEY);divisionData=raw?JSON.parse(raw):makeDivisionDemoData(today());if(!validateDivisionState(divisionData).ok)throw new Error('Invalid division preview');if(!raw)localStorage.setItem(DIVISION_STORE_KEY,JSON.stringify(divisionData));}catch{divisionData=makeDivisionDemoData(today());}
}
const ui={search:'',project:'all',status:'all',assignee:'all',division:'all',layout:'list',calendar:today(),selectedDay:today(),calendarMode:'month',gantt:today(),zoom:'month',chartDays:7};
let undoState=null,toastTimer,dialogContext=null,previousFocus=null,discardClick=false;
const member=id=>state.members.find(x=>x.id===id);
const project=id=>state.projects.find(x=>x.id===id);
const catalogOnly=()=>sharedConfigured?projectCatalog.filter(item=>!project(item.id)):[];
const catalogDivision=item=>item.division||divisionRoutes.find(([,name])=>DIVISION_CODES[name]===item.divisionCode)?.[1]||item.divisionCode;
const avatar=id=>`<span class="avatar mini" title="${h(member(id)?.name||'Unassigned')}">${h(member(id)?.initials||'?')}</span>`;
const statusIcon=s=>`<svg class="status-icon" viewBox="0 0 16 16" aria-hidden="true">${({todo:'<circle cx="8" cy="8" r="5.7"/>',progress:'<circle cx="8" cy="8" r="5.7" opacity=".35"/><path d="M8 2.3a5.7 5.7 0 0 1 5.7 5.7" stroke-width="2.4"/>',blocked:'<path d="M7 2.8a1.2 1.2 0 0 1 2 0l5.1 9a1.2 1.2 0 0 1-1 1.8H2.9a1.2 1.2 0 0 1-1-1.8z"/><path d="M8 6v3 M8 11v.1"/>',done:'<circle cx="8" cy="8" r="7" fill="currentColor" stroke="none"/><path d="m4.8 8 2.1 2.1 4.2-4.2" stroke="white"/>',late:'<circle cx="8" cy="8" r="5.7"/><path d="M8 4.5V8l2 1.3"/>'})[s]||''}</svg>`;
const statusPill=(s,label=STATUSES[s]||'Overdue')=>`<span class="pill ${s}">${statusIcon(s)}${h(label)}</span>`;
const isLate=t=>t.status!=='done'&&t.end<today();
const button=(text,action,extra='',className='')=>{const label=text.replace(/<[^>]+>/g,'').trim();return `<button class="button ${className}" data-action="${action}" ${label&&!extra.includes('aria-label=')?`aria-label="${h(label)}"`:''} ${extra}>${text}</button>`;};
const addButton=(text,action,extra='')=>button(`${icon('plus')}<span class="label">${text}</span>`,action,extra,'primary');
const empty=(title,text,action='',label='')=>`<div class="empty">${icon('projects')}<h3>${h(title)}</h3><p>${h(text)}</p>${action?addButton(label,action):''}</div>`;
const options=(items,value)=>items.map(x=>{const [id,label]=Array.isArray(x)?x:[x,x];return `<option value="${h(id)}" ${id===value?'selected':''}>${h(label)}</option>`}).join('');
const projectOptions=value=>options(state.projects.map(p=>[p.id,p.name]),value);
const memberOptions=value=>options(state.members.map(m=>[m.id,m.name]),value);
function toast(message,undo=false){clearTimeout(toastTimer);$('#toast').innerHTML=`<span>${h(message)}</span>${undo?'<button data-action="undo">Undo</button>':''}`;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,undo?12000:5000);}
async function save(next,message){
  const previous=structuredClone(state);
  if(sharedConfigured){
    try{state=await sharedBackend.commitCoreChange(previous,next);appError='';const deletedProject=previous.projects.some(p=>!state.projects.some(current=>current.id===p.id));undoState=deletedProject?null:previous;render();toast(message,!deletedProject);return true;}
    catch(error){appError=error.message;toast(error.message);return false;}
  }
  next.activity=[{id:uid(),text:message,at:new Date().toISOString()},...next.activity].slice(0,60);
  if(!storageIssue){try{localStorage.setItem(STORE_KEY,JSON.stringify(next));}catch(e){toast('Storage is full or unavailable. Your change was not saved. Export a backup from Workspace.');return false;}}
  undoState=previous;state=next;render();toast(message+(storageIssue?' (This session only.)':''),true);return true;
}
async function undo(){if(!undoState)return;const next=undoState;
  if(sharedConfigured){try{state=await sharedBackend.commitCoreChange(state,next);undoState=null;render();toast('Change undone.');}catch(error){toast(error.message);}return;}
  if(!storageIssue){try{localStorage.setItem(STORE_KEY,JSON.stringify(next));}catch{toast('Unable to save undo. Your current data is unchanged.');return;}}state=next;undoState=null;render();toast('Change undone.');
}
async function commitDivisionChange(next,message){
  const check=validateDivisionState(next);if(!check.ok)throw new Error(check.errors.join(' '));
  if(sharedConfigured){const authoritative=await sharedBackend.commitDivisionState(divisionData,next);divisionData=authoritative;toast(message||'Workspace updated.');return authoritative;}
  try{localStorage.setItem(DIVISION_STORE_KEY,JSON.stringify(next));}catch{throw new Error('Could not save this division preview. Your draft is still open.');}
  divisionData=next;toast(message||'Workspace updated.');return next;
}
async function refreshShared(silent=false){
  if(!sharedBackend||!sessionInfo)return;
  try{
    const [core,divisions,alerts]=await Promise.all([sharedBackend.loadCoreState(),sharedBackend.loadDivisionState(),sharedBackend.listNotifications()]);
    if(!core?.profile||!['members','projects','tasks','events','activity'].every(key=>Array.isArray(core[key])))throw new Error('The shared workspace returned incomplete data.');
    const check=validateDivisionState(divisions);if(!check.ok)throw new Error('Division data could not be loaded.');
    if($('#editor').open||document.querySelector('.dw-modal')){pendingRemote=true;if(!silent)toast('Workspace changed. Finish your draft to load updates.');return;}
    state=core;divisionData=divisions;notifications=alerts;projectCatalog=core.projectCatalog||[];appError='';
    pendingRemote=false;render();if(!silent)toast('Workspace updated by another member.');
  }catch(error){appError=error.message;render();}
}
function watchShared(){
  unsubscribeShared();
  unsubscribeShared=sharedBackend.subscribeToChanges(()=>{
    clearTimeout(remoteRefreshTimer);
    remoteRefreshTimer=setTimeout(()=>refreshShared(false),700);
  });
}
async function initializeShared(){
  try{
    sharedBackend=await createBackend(backendConfig);
    const session=await sharedBackend.getSession();
    if(session){
      sessionInfo=await sharedBackend.bootstrap();
      await refreshShared(true);
      if(sessionInfo?.canManageInvitations){try{[invitations,accessRoster]=await Promise.all([sharedBackend.listInvitations(),sharedBackend.listMembersWithAccess()]);}catch(error){appError=`Workspace access settings could not be loaded: ${error.message}`;}}
      watchShared();
    }
    unsubscribeAuth=sharedBackend.onAuthStateChange((event,session)=>{
      if(event==='SIGNED_OUT'){unsubscribeShared();sessionInfo=null;projectCatalog=[];notifications=[];authReady=true;render();}
      else if(event==='SIGNED_IN'&&session&&!sessionInfo){
        sharedBackend.bootstrap().then(async info=>{sessionInfo=info;await refreshShared(true);watchShared();if(info?.canManageInvitations){try{[invitations,accessRoster]=await Promise.all([sharedBackend.listInvitations(),sharedBackend.listMembersWithAccess()]);}catch(error){appError=`Workspace access settings could not be loaded: ${error.message}`;}}authReady=true;render();}).catch(error=>{appError=error.message;authReady=true;render();});
      }
    });
  }catch(error){appError=error.message;sessionInfo=null;}
  authReady=true;render();
}
function route(){const [raw,id,view]=location.hash.replace(/^#\/?/,'').split('/');const page=raw==='overview'||!raw?'home':raw==='work'?'tasks':raw==='schedule'?'calendar':raw==='workspace'?'division':raw;return {page:['home','division','projects','tasks','calendar','gantt','settings','updates'].includes(page)?page:'home',id,view};}
function go(page){location.hash=page;}
function nav(){const r=route(),active=r.page;const personal=[['home','Home','home'],['tasks','My Work','tasks'],['calendar','Schedule','calendar'],['updates','Updates','flag']];const organization=[['projects','All Projects','projects'],['gantt','Timeline','gantt']];
  const navLinks=entries=>entries.map(([id,label,i])=>`<a class="nav-link" href="#${id}" ${active===id?'aria-current="page"':''}>${icon(i)}<span>${label}</span>${id==='tasks'?`<span class="counter">${state.tasks.filter(t=>t.assignee===state.profile.memberId&&t.status!=='done').length}</span>`:id==='updates'&&notifications.some(n=>!n.read_at)?`<span class="counter">${notifications.filter(n=>!n.read_at).length}</span>`:''}</a>`).join('');
  $('#nav').innerHTML=`<p class="nav-label">PERSONAL</p>${navLinks(personal)}<p class="nav-label">WORKSPACES</p>${divisionRoutes.map(([slug,label,i])=>`<a class="nav-link ${active==='division'&&r.id===slug?'active':''}" href="#workspace/${slug}" ${active==='division'&&r.id===slug?'aria-current="page"':''}>${icon(i)}<span>${h(label)}</span></a>`).join('')}<p class="nav-label">ORGANIZATION</p>${navLinks(organization)}`;
  $('#profile').innerHTML=`<span class="avatar">${h(initials(state.profile.name))}</span><span><strong>${h(state.profile.name)}</strong><p>${sharedConfigured?'Account & workspace':'Preview settings'}</p></span>${icon('settings')}`;
  $('#mobile-nav').innerHTML=personal.slice(0,3).map(([id,label,i])=>`<a href="#${id}" ${active===id?'aria-current="page"':''}>${icon(i)}<span>${label}</span></a>`).join('')+`<button data-action="workspaces-menu" aria-label="Choose division workspace">${icon('projects')}<span>Workspaces</span></button><button data-action="mobile-menu" aria-label="More navigation">${icon('menu')}<span>More</span></button>`;
  $('#crumb').textContent=active==='division'?(divisionNames[r.id]||'Workspace'):([...personal,...organization,['settings','Settings'],].find(x=>x[0]===active)?.[1]||'Home');
  $('#active-workspace-label').textContent=active==='division'?(divisionNames[r.id]||'Division workspace'):'Personal workspace';
}
function heading(title,subtitle,actions=''){return `<header class="page-heading"><div><h1>${h(title)}</h1><p>${h(subtitle)}</p></div><div class="heading-actions">${actions}</div></header>`;}
function taskMatches(t,defaultMine=false){return (!defaultMine||t.assignee===state.profile.memberId)&&(ui.project==='all'||t.projectId===ui.project)&&(ui.status==='all'||(ui.status==='overdue'?isLate(t):t.status===ui.status))&&(ui.assignee==='all'||t.assignee===ui.assignee)&&(!ui.search||`${t.title} ${project(t.projectId)?.name} ${member(t.assignee)?.name}`.toLowerCase().includes(ui.search.toLowerCase()));}
function taskStatusControl(t){return `<label class="status-control">${statusPill(t.status)}<select data-status-task="${h(t.id)}" aria-label="Status for ${h(t.title)}">${options(Object.entries(STATUSES),t.status)}</select></label>`;}
function taskTable(tasks,compact=false){return tasks.length?`<div class="table-scroll"><table class="task-table ${compact?'compact':''}"><thead><tr><th><span class="sr-only">Complete</span></th><th>Task</th><th class="desktop-cell">Status</th><th class="desktop-cell assignee-column">Assignee</th><th>Due date</th></tr></thead><tbody>${tasks.map(t=>`<tr data-task-row="${h(t.id)}"><td><input class="task-check" type="checkbox" data-complete="${h(t.id)}" aria-label="Complete ${h(t.title)}" ${t.status==='done'?'checked':''}></td><td><button class="task-title ${t.status==='done'?'done-title':''}" data-action="edit-task" data-id="${h(t.id)}">${h(t.title)}</button><span class="sub">${h(project(t.projectId)?.name||'')}${t.dependsOn?' · Dependency':''}</span><span class="task-mobile-status">${taskStatusControl(t)}</span></td><td class="desktop-cell">${taskStatusControl(t)}</td><td class="desktop-cell assignee-column"><span class="assignee">${avatar(t.assignee)}<span class="name">${h(member(t.assignee)?.name)}</span></span></td><td class="date-cell ${isLate(t)?'text-overdue':''}">${fmt(t.end)}${isLate(t)?`<span class="overdue-condition">${statusPill('late')}</span>`:''}</td></tr>`).join('')}</tbody></table></div>`:empty('No tasks here','Try a different filter or add a task to get started.');}
const artColors={peach:['#FF8A62','#FFDCC7','#C9613B'],blue:['#92BAE5','#DEEEFF','#6286AD'],butter:['#F1CF70','#FFF6CC','#C2973C'],sage:['#92AE8E','#E4EECF','#5D7C5C'],cream:['#FFF0D1','#FFFBEF','#D6B897']};
const palettes=[['peach','blue','cream'],['butter','sage','cream'],['sage','blue','cream'],['peach','butter','sage']];
const artTiming=new Map();
function cover(p){const color=((p.color%4)+4)%4;if(!artTiming.has(p.id))artTiming.set(p.id,Array.from({length:3},()=>({duration:18+Math.random()*12,phase:-Math.random()*30,x:Math.random()*6-3,y:Math.random()*6-3,tx:Math.random()*12-6,ty:Math.random()*12-6,rotation:Math.random()*30-15})));const timings=artTiming.get(p.id);return `<span class="project-artwork" data-color="${color}" aria-hidden="true">${palettes[color].map((key,i)=>{const [base,shine,shade]=artColors[key],t=timings[i];return `<span class="art-form" style="--color:${base};--shine:${shine};--shade:${shade};--duration:${t.duration}s;--phase:${t.phase}s;--x:${t.x}px;--y:${t.y}px;--to-x:${t.tx}px;--to-y:${t.ty}px;--rotation:${t.rotation}deg"></span>`;}).join('')}<span class="art-grain"></span><span class="art-light"></span><span class="cover-icon"><svg viewBox="0 0 34 40"><rect x="4" y="3" width="26" height="34" rx="3"/><path d="M10 12h14M10 18h14M10 24h14M10 30h9" fill="none" stroke="#d7d7d3" stroke-width="2" stroke-linecap="round"/></svg></span></span>`;}
function projectStatus(p){const ts=state.tasks.filter(t=>t.projectId===p.id);return ts.length&&ts.every(t=>t.status==='done')?'done':ts.some(t=>t.status==='blocked')?'blocked':ts.some(t=>t.status==='progress'||t.status==='done')?'progress':'todo';}
function projectCard(p){const pr=progress(state,p.id);return `<article class="card project-card"><div class="project-identity">${cover(p)}<div class="project-copy"><button class="project-title" data-action="open-project" data-id="${h(p.id)}"><h3>${h(p.name)}</h3></button><p class="project-meta">${h(p.division)}</p>${statusPill(projectStatus(p))}</div></div>${button(icon('edit'),'edit-project',`data-id="${h(p.id)}" aria-label="Edit ${h(p.name)}"`,'icon-only project-edit')}<div class="project-progress"><div class="progress-label"><span>${pr.done} of ${pr.total} tasks complete</span><strong>${pr.percent}%</strong></div><div class="progress-track" role="progressbar" aria-label="${h(p.name)} progress" aria-valuenow="${pr.percent}" aria-valuemin="0" aria-valuemax="100"><span style="width:${pr.percent}%"></span></div></div><div class="project-footer"><span class="lead">${avatar(p.owner)}${h(member(p.owner)?.name)}</span><span>${fmt(p.end)}</span></div></article>`;}
function catalogCard(item){return `<article class="card v03-project-summary"><div><span class="v03-eyebrow">SHARED SUMMARY</span><h3>${h(item.name)}</h3><p>${h(catalogDivision(item))}</p></div><div class="v03-project-summary-foot"><span>${h(item.status||'Planned')}</span><span>${fmt(item.end)}</span></div></article>`;}
function projectMini(p){const pr=progress(state,p.id);return `<button class="project-mini" data-action="open-project" data-id="${h(p.id)}">${cover(p)}<span class="project-mini-copy"><strong>${h(p.name)}</strong><span class="progress-label"><span>${pr.done}/${pr.total} tasks</span><span>${pr.percent}%</span></span><span class="progress-track"><span style="width:${pr.percent}%"></span></span></span></button>`;}
function chartEntries(){return Array.from({length:ui.chartDays},(_,i)=>{const date=addDays(today(),i-ui.chartDays+1),ts=state.tasks.filter(t=>t.completedAt===date&&t.status==='done');return {date,count:ts.length,titles:ts.map(t=>t.title),label:fmt(date),axis:ui.chartDays===7?fmt(date,{weekday:'short'}):fmt(date,{day:'numeric',month:'short'})};});}
function agendaRows(events){return events.length?events.map(e=>`<button class="agenda-row" data-action="edit-event" data-id="${h(e.id)}"><span class="agenda-date">${fmt(e.date,{month:'short'})}<strong>${day(e.date).getDate()}</strong></span><span class="agenda-copy"><strong>${h(e.title)}</strong><p>${h(e.time)} · ${e.duration} min</p><p>${h(e.location||project(e.projectId)?.name||'Personal event')}</p></span>${icon('chevron')}</button>`).join(''):empty('Room in your schedule','Add a meeting or a project milestone.','new-event','Add event');}
function overview(){
  const me=state.profile.memberId;
  const mine=state.tasks.filter(t=>t.assignee===me&&t.status!=='done').sort((a,b)=>a.end.localeCompare(b.end));
  const taskRow=t=>`<div class="v03-row"><input class="task-check" type="checkbox" data-complete="${h(t.id)}" aria-label="Complete ${h(t.title)}"><div class="v03-row-main"><button class="task-title" data-action="edit-task" data-id="${h(t.id)}">${h(t.title)}</button><span class="sub">${h(project(t.projectId)?.name||'Project')} · ${fmt(t.end)}</span></div>${statusPill(isLate(t)?'late':t.status)}</div>`;
  const divisionRow=(title,meta,href,tone='info',label='Action')=>`<a class="v03-row v03-home-link" href="${h(href)}"><span class="v03-row-main"><strong>${h(title)}</strong><span class="sub">${h(meta)}</span></span><span class="v03-badge" data-tone="${tone}">${h(label)}</span></a>`;
  const approvals=divisionData.financeRequests.filter(x=>sessionInfo?.canApproveFinance||!sharedConfigured).filter(x=>x.requesterId!==me&&['submitted','review'].includes(x.stageId)).map(x=>divisionRow(x.title,'Legal & Finance · approval requested','#workspace/legal-finance','warning','Approval'));
  const decisions=divisionData.decisions.filter(x=>x.ownerId===me&&x.status==='pending').map(x=>divisionRow(x.title,'Strategy & Growth · decision needed','#workspace/strategy-growth','info','Decision'));
  const onboarding=divisionData.onboarding.filter(x=>x.ownerId===me&&x.stageId!=='complete'&&x.dueDate<=today()).map(x=>divisionRow(x.title,'Human Resource · onboarding','#workspace/human-resource','warning','Due'));
  const needs=[...mine.filter(t=>t.status==='blocked'||isLate(t)||t.end===today()).map(taskRow),...approvals,...decisions,...onboarding].slice(0,5);
  const needBody=needs.join('')||'<div class="v03-empty"><strong>Nothing demanding your attention.</strong><span>Your assigned work is clear for now.</span></div>';
  const todayEvents=state.events.filter(e=>e.date===today()).sort((a,b)=>a.time.localeCompare(b.time));
  const todayTasks=mine.filter(t=>t.end===today());
  const todayRows=[...todayEvents.map(e=>`<button class="v03-row v03-row-button" data-action="edit-event" data-id="${h(e.id)}"><span class="v03-time">${h(e.time)}</span><span class="v03-row-main"><strong>${h(e.title)}</strong><span class="sub">${h(e.location||project(e.projectId)?.name||'Meeting')}</span></span>${icon('chevron')}</button>`),...todayTasks.map(t=>`<button class="v03-row v03-row-button" data-action="edit-task" data-id="${h(t.id)}"><span class="v03-time">Due</span><span class="v03-row-main"><strong>${h(t.title)}</strong><span class="sub">${h(project(t.projectId)?.name||'Project')}</span></span>${icon('chevron')}</button>`),...divisionData.deliverables.filter(x=>x.publishDate===today()&&x.ownerId===me).map(x=>divisionRow(x.title,'Marketing, Communication & IT · publish today','#workspace/marketing-comms-it','info','Publish'))].slice(0,6);
  const todayBody=todayRows.join('')||'<div class="v03-empty"><strong>A clear day.</strong><span>Meetings and deadlines for today will appear here.</span></div>';
  const ownedInitiatives=divisionData.initiatives.filter(x=>x.ownerId===me&&!['completed','paused'].includes(x.stageId)).slice(0,2).map(x=>divisionRow(x.title,'Strategy & Growth · initiative','#workspace/strategy-growth','info',x.stageId));
  const ownedContent=divisionData.deliverables.filter(x=>x.ownerId===me&&x.stageId!=='published').slice(0,2).map(x=>divisionRow(x.title,'Marketing, Communication & IT · content','#workspace/marketing-comms-it','info',x.stageId));
  const myRows=[...mine.slice(0,4).map(taskRow),...ownedInitiatives,...ownedContent].slice(0,6);
  const myWork=myRows.join('')||'<div class="v03-empty"><strong>No open work assigned to you.</strong><span>Browse a division workspace to see what is moving.</span></div>';
  const primary=divisionRoutes.find(([,name])=>DIVISION_CODES[name]===sessionInfo?.profile?.primary_division_code);
  const browseBody=primary?`<a class="v03-home-workspace-link" href="#workspace/${primary[0]}"><span class="v03-prism v03-prism--identity v03-home-mark" data-prism-priority="1"><span class="v03-prism-content">d.</span></span><span><strong>${h(primary[1])}</strong><small>Open your division workspace ${icon('arrow')}</small></span></a>`:`<div class="v03-home-workspace-list">${divisionRoutes.filter(([slug])=>!['consulting','external-engagement'].includes(slug)).map(([slug,name])=>`<a href="#workspace/${slug}">${h(name)}${icon('arrow')}</a>`).join('')}</div>`;
  const activity=[...new Map([...state.activity,...divisionData.activity].map(x=>[x.id,x])).values()].sort((a,b)=>String(b.at||b.occurredAt).localeCompare(String(a.at||a.occurredAt))).slice(0,4);
  const recent=activity.map(a=>`<li><span class="v03-activity-mark"></span><span>${h(a.text||a.action||a.title||a.summary||'Workspace updated')}</span></li>`).join('');
  return `<div class="v03-page v03-home">${heading(`Welcome back, ${state.profile.name.split(' ')[0]}`,fullDate(today()),addButton('Create task','new-task'))}<div class="v03-home-grid"><section class="v03-panel v03-home-needs"><div class="v03-panel-head"><div><span class="v03-eyebrow">PERSONAL</span><h2>Needs You</h2></div><span class="v03-count">${needs.length}</span></div><div class="v03-list">${needBody}</div></section><section class="v03-panel v03-home-today"><div class="v03-panel-head"><div><span class="v03-eyebrow">${h(fmt(today(),{weekday:'long'}).toUpperCase())}</span><h2>Today</h2></div><a class="link-button" href="#calendar">Schedule ${icon('arrow')}</a></div><div class="v03-list">${todayBody}</div></section><section class="v03-panel v03-home-work"><div class="v03-panel-head"><div><span class="v03-eyebrow">ASSIGNED TO YOU</span><h2>My Work</h2></div><a class="link-button" href="#tasks">View all ${icon('arrow')}</a></div><div class="v03-list">${myWork}</div></section></div><div class="v03-home-secondary"><section class="v03-panel"><div class="v03-panel-head"><div><span class="v03-eyebrow">WORKSPACES</span><h2>${primary?'Your division':'Explore workspaces'}</h2></div></div>${browseBody}</section><section class="v03-panel"><div class="v03-panel-head"><div><span class="v03-eyebrow">RECENT MOVEMENT</span><h2>What changed</h2></div><a class="link-button" href="#updates">All updates ${icon('arrow')}</a></div><ul class="v03-activity-list">${recent||'<li>No meaningful changes recorded yet.</li>'}</ul></section></div></div>`;
}
function taskFilters(allowMine=false){return `<div class="filters"><input class="input search-input" id="search" type="search" data-search placeholder="Search tasks…" aria-label="Search tasks" value="${h(ui.search)}"><select data-filter="project" aria-label="Filter by project">${options([['all','All projects'],...state.projects.map(p=>[p.id,p.name])],ui.project)}</select><select data-filter="status" aria-label="Filter by status">${options([['all','All statuses'],...Object.entries(STATUSES),['overdue','Overdue']],ui.status)}</select><select data-filter="assignee" aria-label="Filter by assignee">${options([['all','All assignees'],...state.members.map(m=>[m.id,m.name])],ui.assignee)}</select></div>`;}
function board(tasks){return `<div class="board">${Object.entries(STATUSES).map(([id,label])=>`<section class="board-column" data-drop-status="${id}" aria-label="${label}"><div class="board-title">${statusPill(id)}<span class="small muted">${tasks.filter(t=>t.status===id).length}</span></div>${tasks.filter(t=>t.status===id).map(t=>`<button class="board-task" draggable="true" data-drag-task="${h(t.id)}" data-action="edit-task" data-id="${h(t.id)}"><span class="small muted">${h(project(t.projectId)?.name)}</span><p>${h(t.title)}</p><span class="board-foot"><span class="${isLate(t)?'text-overdue':''}">${fmt(t.end)}</span>${avatar(t.assignee)}</span></button>`).join('')}</section>`).join('')}</div>`;}
function projectsPage(id){if(id){const p=project(id);if(!p)return heading('Project not found','This project may have been deleted.',button('All projects','navigate','data-to="projects"'));
  const pr=progress(state,id),ts=state.tasks.filter(t=>t.projectId===id&&(!ui.search||t.title.toLowerCase().includes(ui.search.toLowerCase()))&&(ui.status==='all'||t.status===ui.status));
  return heading(p.name,`${p.division} Division`,button(icon('edit')+'<span class="label">Edit project</span>','edit-project',`data-id="${h(id)}"`)+addButton('Add task','new-task',`data-project="${h(id)}"`))+`<section class="card card-body"><div class="project-detail-head">${cover(p)}<div>${statusPill(projectStatus(p))}<p>${h(p.description||'Add a description to share what this project is working toward.')}</p><div class="project-detail-meta"><span>Lead: ${h(member(p.owner)?.name)}</span><span>${fmt(p.start)} – ${fmt(p.end)}</span><span>${pr.done}/${pr.total} tasks completed · ${pr.percent}%</span></div></div></div></section><section class="section"><div class="page-tools"><div class="filters"><input class="input search-input" data-search type="search" placeholder="Search project tasks…" aria-label="Search project tasks" value="${h(ui.search)}"><select data-filter="status" aria-label="Filter status">${options([['all','All statuses'],...Object.entries(STATUSES)],ui.status)}</select></div><div class="actions">${layoutSwitch()}${button(icon('gantt')+'Timeline','project-timeline',`data-project="${h(id)}"`)}</div></div>${ui.layout==='board'?board(ts):`<div class="card">${taskTable(ts)}</div>`}</section>`;
  }
  const list=state.projects.filter(p=>(ui.division==='all'||p.division===ui.division)&&(!ui.search||`${p.name} ${p.division}`.toLowerCase().includes(ui.search.toLowerCase())));
  const summaries=catalogOnly().filter(item=>(ui.division==='all'||catalogDivision(item)===ui.division)&&(!ui.search||`${item.name} ${catalogDivision(item)}`.toLowerCase().includes(ui.search.toLowerCase())));
  return heading('Projects','A shared plan for the work that matters.',addButton('New project','new-project'))+`<div class="page-tools"><div class="filters"><input type="search" class="input search-input" data-search aria-label="Search projects" placeholder="Search projects…" value="${h(ui.search)}"><select data-filter="division" aria-label="Filter by division">${options([['all','All divisions'],...DIVISIONS],ui.division)}</select></div><span class="small muted">${list.length+summaries.length} visible projects</span></div><div class="project-grid">${list.map(projectCard).join('')}${summaries.map(catalogCard).join('')}</div>${!list.length&&!summaries.length?empty('No projects found','Create a project or change your filters.','new-project','Create project'):''}`;
}
function layoutSwitch(){return `<div class="segmented" aria-label="Task layout"><button data-action="layout" data-layout="list" aria-pressed="${ui.layout==='list'}">List</button><button data-action="layout" data-layout="board" aria-pressed="${ui.layout==='board'}">Board</button></div>`;}
function tasksPage(){const ts=state.tasks.filter(t=>taskMatches(t)).sort((a,b)=>a.end.localeCompare(b.end));return heading('Tasks','Assign responsibilities, track blockers, and keep work moving.',addButton('New task','new-task'))+`<div class="page-tools">${taskFilters()}<div class="actions">${button('Assigned to me','mine', '',ui.assignee===state.profile.memberId?'primary':'')}${layoutSwitch()}</div></div>${ui.layout==='board'?board(ts):`<section class="card">${taskTable(ts)}</section>`}`;}
function calendarItems(date){return [...state.events.filter(e=>e.date===date&&(ui.project==='all'||e.projectId===ui.project)).sort((a,b)=>a.time.localeCompare(b.time)).map(e=>({type:'event',item:e})),...state.tasks.filter(t=>t.end===date&&(ui.project==='all'||t.projectId===ui.project)).map(t=>({type:'task',item:t}))];}
function agendaRange(start,end){let html='';for(let d=start;d<=end;d=addDays(d,1)){const items=calendarItems(d);if(!items.length)continue;html+=`<div class="agenda-group-date">${fullDate(d)}</div>`+items.map(({type,item:t})=>type==='event'?agendaRows([t]):`<button class="agenda-row" data-action="edit-task" data-id="${h(t.id)}"><span class="agenda-date">${icon('tasks')}</span><span class="agenda-copy"><strong>${h(t.title)}</strong><p>Due date · ${h(project(t.projectId)?.name)}</p></span>${statusPill(t.status)}</button>`).join('');}return html||empty('Nothing scheduled here','Choose another date or add an event.','new-event','Add event');}
function calendarPage(){const d=day(ui.calendar);const first=iso(new Date(d.getFullYear(),d.getMonth(),1));const end=iso(new Date(d.getFullYear(),d.getMonth()+1,0));const start=addDays(first,-((day(first).getDay()+6)%7));const days=Array.from({length:42},(_,i)=>addDays(start,i));const title=fmt(first,{month:'long',year:'numeric'});
  return heading('Schedule','Meetings and task deadlines, in one place.',addButton('New event','new-event'))+`<div class="page-tools"><div class="actions">${button(icon('left'),'calendar-prev','aria-label="Previous month"','icon-only')}<h2>${title}</h2>${button(icon('chevron'),'calendar-next','aria-label="Next month"','icon-only')}${button('Today','calendar-today')}</div><div class="filters" style="width:auto"><select data-filter="project" aria-label="Schedule project">${options([['all','All projects'],...state.projects.map(p=>[p.id,p.name])],ui.project)}</select><div class="segmented"><button data-action="calendar-mode" data-mode="month" aria-pressed="${ui.calendarMode==='month'}">Month</button><button data-action="calendar-mode" data-mode="agenda" aria-pressed="${ui.calendarMode==='agenda'}">Agenda</button></div></div></div><section class="card">${ui.calendarMode==='agenda'?agendaRange(first,end):`<div class="calendar-desktop"><div class="calendar-weekdays">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<span>${x}</span>`).join('')}</div><div class="calendar-grid">${days.map(date=>{const items=calendarItems(date);return `<div class="calendar-day ${date<first||date>end?'outside':''} ${date===today()?'is-today':''}"><button class="day-number" data-action="new-event" data-date="${date}" aria-label="Add event on ${fullDate(date)}">${day(date).getDate()}</button>${items.slice(0,3).map(({type,item:t})=>`<button class="calendar-chip ${type==='event'?'event':t.status+(isLate(t)?' late':'')}" data-action="edit-${type}" data-id="${h(t.id)}" title="${h(t.title)}">${type==='task'?statusIcon(t.status):icon('calendar')}<span>${type==='event'?h(t.time)+' ':''}${h(t.title)}</span></button>`).join('')}${items.length>3?`<button class="calendar-more" data-action="day-agenda" data-date="${date}">+${items.length-3} more</button>`:''}</div>`}).join('')}</div></div><div class="calendar-mobile"><div class="mobile-month"><div class="mobile-weekdays">${['M','T','W','T','F','S','S'].map(x=>`<span>${x}</span>`).join('')}</div><div class="mobile-month-days">${days.map(date=>`<button class="${date<first||date>end?'outside':''} ${date===ui.selectedDay?'selected':''} ${date===today()?'is-today':''}" data-action="select-day" data-date="${date}" aria-label="${fullDate(date)}: ${calendarItems(date).length} items" aria-pressed="${date===ui.selectedDay}"><span>${day(date).getDate()}</span>${calendarItems(date).length?'<i></i>':''}</button>`).join('')}</div></div>${agendaRange(ui.selectedDay,ui.selectedDay)}</div>`}</section><div class="calendar-key"><span>Task due dates</span><span>Meetings & events · Local time</span></div>`;
}
function ganttRange(){const d=day(ui.gantt);return ui.zoom==='month'?{start:iso(new Date(d.getFullYear(),d.getMonth(),1)),count:new Date(d.getFullYear(),d.getMonth()+1,0).getDate(),width:34}:{start:addDays(ui.gantt,-((d.getDay()+6)%7)),count:14,width:64};}
function ganttPage(){const range=ganttRange();const end=addDays(range.start,range.count-1);const projects=state.projects.filter(p=>ui.project==='all'||p.id===ui.project);let rows='';let shown=0;const bar=(start,finish)=>({left:Math.max(0,diffDays(start,range.start))*range.width,width:(Math.min(range.count-1,diffDays(finish,range.start))-Math.max(0,diffDays(start,range.start))+1)*range.width});
  for(const p of projects){const ts=state.tasks.filter(t=>t.projectId===p.id&&t.start<=end&&t.end>=range.start);if(!ts.length)continue;const b=bar(p.start,p.end);rows+=`<button class="gantt-label group" data-action="open-project" data-id="${h(p.id)}"><span>${h(p.name)}</span></button><div class="gantt-track group"><div class="gantt-project-bar" style="left:${b.left}px;width:${Math.max(0,b.width)}px"></div></div>`;for(const t of ts){shown++;const b=bar(t.start,t.end);rows+=`<button class="gantt-label" data-action="edit-task" data-id="${h(t.id)}">${avatar(t.assignee)}<span>${h(t.title)}</span></button><div class="gantt-track"><div class="today-line"></div><div role="button" tabindex="0" class="gantt-bar ${t.status}" data-gantt-task="${h(t.id)}" data-action="edit-task" data-id="${h(t.id)}" aria-label="${h(t.title)}, ${STATUSES[t.status]}, ${fmt(t.start)} to ${fmt(t.end)}. Enter to edit; arrows to move; Shift and arrows to resize." title="${h(t.title)} · ${fmt(t.start)}–${fmt(t.end)}${t.dependsOn?' · Depends on '+h(state.tasks.find(x=>x.id===t.dependsOn)?.title):''}" style="left:${b.left+3}px;width:${Math.max(12,b.width-6)}px">${statusIcon(t.status)}<span>${h(t.title)}</span>${t.end<=end?'<i class="resize-handle" aria-hidden="true"></i>':''}</div></div>`;}}
  return heading('Gantt timeline','See the plan, connect responsibilities, and adjust dates.',addButton('New task','new-task'))+`<div class="page-tools"><div class="actions">${button(icon('left'),'gantt-prev','aria-label="Previous timeline period"','icon-only')}<h2>${fmt(range.start,{month:'short',day:'numeric'})} – ${fmt(end,{month:'short',day:'numeric',year:'numeric'})}</h2>${button(icon('chevron'),'gantt-next','aria-label="Next timeline period"','icon-only')}${button('Today','gantt-today')}</div><div class="filters" style="width:auto"><select data-filter="project" aria-label="Timeline project">${options([['all','All projects'],...state.projects.map(p=>[p.id,p.name])],ui.project)}</select><div class="segmented"><button data-action="zoom" data-zoom="month" aria-pressed="${ui.zoom==='month'}">Month</button><button data-action="zoom" data-zoom="week" aria-pressed="${ui.zoom==='week'}">2 weeks</button></div></div></div><section class="card">${shown?`<div class="gantt-scroll" data-range="${range.start}/${ui.zoom}/${h(ui.project)}"><div class="gantt" style="--timeline-width:${range.count*range.width}px;--day-width:${range.width}px;--today-x:${diffDays(today(),range.start)*range.width}px"><div class="gantt-label header">Project / task</div><div class="gantt-days">${Array.from({length:range.count},(_,i)=>{const date=addDays(range.start,i);return `<div class="gantt-day ${date===today()?'today':''}">${fmt(date,{weekday:'short'})}<b>${day(date).getDate()}</b></div>`}).join('')}</div>${rows}</div></div>`:empty('No tasks in this period','Use the arrows to browse dates or add a scheduled task.','new-task','New task')}<p class="gantt-hint">Drag a bar to move a task. Drag its right edge to change the due date. Select a task to edit details and dependencies. Keyboard: ← / → moves one day; Shift + arrow adjusts the end. Project dates expand to include tasks.</p></section>`;
}
function settingsPage(){return heading('Workspace settings',sharedConfigured?'Your account, members, and shared workspace access.':'Manage this local design preview and its backups.')+`<div class="settings-grid"><section class="card"><div class="card-head"><h2>People</h2>${sharedConfigured?'':button(icon('plus'),'new-member','aria-label="Add a preview member"','icon-only')}</div><div class="card-body"><p class="small muted">${sharedConfigured?'Accounts and division access are managed through invitations.':'Preview members are local records, not sign-in accounts.'}</p>${state.members.map(m=>`<div class="member-row">${avatar(m.id)}<div><strong>${h(m.name)}</strong><p class="small muted">${m.id===state.profile.memberId?'You':'Workspace member'}</p></div>${sharedConfigured?'':button(icon('edit'),'edit-member',`data-id="${h(m.id)}" aria-label="Edit ${h(m.name)}" style="margin-left:auto"`,'icon-only')}</div>`).join('')}${sharedConfigured?button('Sign out','sign-out','','') :''}</div></section><div><section class="card"><div class="card-head"><h2>${sharedConfigured?'Shared workspace':'Saved on this device'}</h2>${icon('download')}</div><div class="card-body"><p class="muted small">${sharedConfigured?'Your changes are saved to the DWDG shared workspace. Importing an older local backup requires an administrator review.':'Your original v1 projects and tasks stay in this browser. Division preview data is kept separately.'}</p><div class="actions">${button(icon('download')+'Export local backup','export')}${button(icon('upload')+'Import backup','import')}</div>${storageIssue?button('Save this session as workspace','recover','','danger'):''}</div></section><section class="section card"><div class="card-head"><h2>Recent activity</h2></div><div class="card-body">${state.activity.slice(0,8).map(a=>`<div class="activity-row"><span class="activity-dot"></span><div><p>${h(a.text||a.summary||'Workspace updated')}</p><small>${h(new Date(a.at||a.created_at||Date.now()).toLocaleString('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}))}</small></div></div>`).join('')||'<p class="small muted">Meaningful changes will appear here.</p>'}</div></section></div></div>`;}
function updatesPage(){const activity=[...new Map([...state.activity,...divisionData.activity].map(a=>[a.id,a])).values()].sort((a,b)=>String(b.at||b.created_at).localeCompare(String(a.at||a.created_at))).slice(0,30);return heading('Updates','Meaningful changes across work you can access.')+`<section class="v03-panel"><div class="v03-panel-head"><h2>Recent movement</h2></div><div class="v03-list">${activity.length?activity.map(a=>`<div class="v03-row"><span class="v03-activity-mark"></span><div class="v03-row-main"><strong>${h(a.text||a.action||a.summary||'Workspace updated')}</strong><span class="sub">${h(new Date(a.at||a.created_at||Date.now()).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'}))}</span></div></div>`).join(''):'<div class="v03-empty"><strong>No changes recorded yet.</strong><span>Project and division updates will appear here.</span></div>'}</div></section>`;}
function divisionPage(slug){if(!divisionNames[slug])return heading('Workspace not found','Choose a division from the sidebar.');if(['external-engagement','consulting'].includes(slug)){const ps=state.projects.filter(p=>p.division===divisionNames[slug]||(slug==='external-engagement'&&p.division==='Client Engagement'));const summaries=catalogOnly().filter(item=>catalogDivision(item)===divisionNames[slug]);const rows=ps.map(p=>`<div class="v03-row"><div class="v03-row-main"><strong>${h(p.name)}</strong><span class="sub">${fmt(p.end)} · ${h(p.division)}</span></div><button class="button" data-action="open-project" data-id="${h(p.id)}">Open</button></div>`).join('')+summaries.map(item=>`<div class="v03-row"><div class="v03-row-main"><strong>${h(item.name)}</strong><span class="sub">${fmt(item.end)} · ${h(item.status||'Planned')}</span></div><span class="sub">Summary only</span></div>`).join('');return `<div class="v03-page">${heading(divisionNames[slug],'Shared projects and division information.') }<section class="v03-panel"><div class="v03-panel-head"><h2>Shared project summaries</h2></div><div class="v03-panel-body">${rows||'<div class="v03-empty"><strong>No shared projects yet.</strong><span>This division is visible; its full workspace is scheduled for a later iteration.</span></div>'}</div></section></div>`;}return `<div id="division-mount" class="v03-page" aria-live="polite"></div>`;}
let disposeDivision=()=>{},disposeExtras=()=>{};
function render(){
  const oldTimeline=$('.gantt-scroll');const timelineState=oldTimeline?{key:oldTimeline.dataset.range,left:oldTimeline.scrollLeft,top:oldTimeline.scrollTop}:null;const focus=document.activeElement;const searchFocused=focus?.matches('[data-search]');const pos=searchFocused?focus.selectionStart:null;const r=route();disposeDivision();disposeDivision=()=>{};disposeExtras();disposeExtras=()=>{};
  if(sharedConfigured&&!authReady){$('#nav').innerHTML='';$('#mobile-nav').innerHTML='';$('#content').innerHTML='<section class="v03-auth-screen"><h1>Opening DWDG Workspace…</h1><p>Checking your session and access.</p></section>';return;}
  if(sharedConfigured&&!sessionInfo){$('#nav').innerHTML='';$('#mobile-nav').innerHTML='';$('#content').innerHTML=`<section class="v03-auth-screen"><span class="v03-eyebrow">DWDG UII</span><h1>Your work, in one place.</h1><p>Sign in with the Google account invited to DWDG Workspace.</p>${appError?`<p class="notice error" role="alert">${h(appError)}</p>`:''}<div class="actions">${sharedBackend?button('Continue with Google','sign-in','','primary'):button('Retry connection','retry-session','','primary')}${appError&&sharedBackend?button('Retry access','retry-session')+button('Use another account','switch-account'):''}</div></section>`;return;}
  nav();const pages={home:overview,projects:()=>projectsPage(r.id),tasks:tasksPage,calendar:calendarPage,gantt:ganttPage,settings:settingsPage,updates:updatesPage,division:()=>divisionPage(r.id)};$('#content').innerHTML=(storageIssue?`<div class="notice error">${h(storageIssue)}</div>`:'')+(appError?`<div class="notice error" role="alert">${h(appError)}</div>`:'')+pages[r.page]()+((r.page==='settings')?adminSettingsPage()+adminManagementPanels():'')+((r.page==='updates')?notificationPanel():'')+`<footer class="page-footer"><span>DWDG UII · Do well. Do good. Together.</span><span>${sharedConfigured?'Shared workspace':'Local design preview'}</span></footer>`;
  const timeline=$('.gantt-scroll');if(timeline){const range=ganttRange();timeline.scrollLeft=timelineState?.key===timeline.dataset.range?timelineState.left:Math.max(0,(diffDays(today(),range.start)-Math.min(5,Math.max(0,Math.floor((timeline.clientWidth-timeline.querySelector('.gantt-label').getBoundingClientRect().width)/range.width/2))))*range.width);timeline.scrollTop=timelineState?.key===timeline.dataset.range?timelineState.top:0;}
  if(r.page==='division'&&$('#division-mount')){const code=DIVISION_CODES[divisionNames[r.id]];const canEdit=!sharedConfigured||sessionInfo?.canEditDivisionCodes?.includes(code);const canManageStages=!sharedConfigured||sessionInfo?.headDivisionCodes?.includes(code);const canApprove=!sharedConfigured||(r.id==='legal-finance'&&sessionInfo?.canApproveFinance);const canViewSensitive=!sharedConfigured||sessionInfo?.profile?.global_role==='super_admin'||sessionInfo?.memberDivisionCodes?.includes(code)||(r.id==='legal-finance'&&sessionInfo?.canApproveFinance);disposeDivision=mountDivisionWorkspace($('#division-mount'),{slug:r.id,data:divisionData,members:state.members,projects:state.projects,currentUserId:state.profile.memberId,canEdit,canManageStages,canSubmitFinanceRequest:r.id==='legal-finance'&&!!sessionInfo?.user,canApprove,canViewSensitive,onChange:commitDivisionChange,onModalClose:()=>{if(pendingRemote)refreshShared(true);}});}
  if(r.page==='projects'&&r.id&&project(r.id)){const container=document.createElement('div');container.id='project-extras';$('.page-footer').before(container);const p=project(r.id);const code=DIVISION_CODES[p.division];const canEdit=!sharedConfigured||sessionInfo?.canEditDivisionCodes?.includes(code);disposeExtras=mountProjectExtras(container,{project:p,projects:state.projects,members:state.members,tasks:state.tasks,backend:sharedBackend,sharedConfigured,canEdit,currentUserId:state.profile.memberId,onUpdated:()=>{if(sharedConfigured)refreshShared(true);}});}
  if(searchFocused){const input=$('[data-search]');input?.focus();try{input?.setSelectionRange(pos,pos)}catch{}}
}
function field(label,name,type,value,extra='',full=false){return `<div class="field ${full?'full':''}"><label for="f-${name}">${label}</label><input id="f-${name}" class="input" name="${name}" type="${type}" value="${h(value)}" ${extra}></div>`;}
function selectField(label,name,html,full=false){return `<div class="field ${full?'full':''}"><label for="f-${name}">${label}</label><select name="${name}" id="f-${name}">${html}</select></div>`;}
function textField(label,name,value){return `<div class="field full"><label for="f-${name}">${label}</label><textarea name="${name}" id="f-${name}" maxlength="4000">${h(value)}</textarea></div>`;}
function openDialog(title,content,actions='',context=null){previousFocus=document.activeElement;dialogContext=context;$('#editor').innerHTML=`<div class="dialog-head"><h2 id="dialog-title">${h(title)}</h2>${button(icon('close'),'close-dialog','aria-label="Close dialog"','icon-only')}</div>${content}${actions}`;$('#editor').showModal();$('#editor').querySelector('input:not([type=hidden])')?.focus();}
function closeDialog(){const id=dialogContext?.id;$('#editor').close();dialogContext=null;if(previousFocus?.isConnected)previousFocus.focus();else if(id)document.querySelector(`[data-id="${CSS.escape(id)}"]`)?.focus();if(pendingRemote)refreshShared(true);}
function formDialog(title,fields,context,deleteAction=''){
  openDialog(title,`<form id="edit-form"><div class="dialog-body"><div id="form-error" role="alert" tabindex="-1" hidden></div><div class="form-grid">${fields}</div></div><div class="dialog-actions">${deleteAction?button(icon('trash')+'Delete',deleteAction,`data-id="${h(context.id)}" type="button"`,'danger'):''}${button('Cancel','close-dialog','type="button"')}<button class="button primary" type="submit">Save ${context.kind}</button></div></form>`,'',context);
}
function taskDialog(id='',projectId=''){
  if(!state.projects.length){projectDialog();toast('Create a project first, then add its tasks.');return;}
  const t=state.tasks.find(t=>t.id===id)||{id:uid(),title:'',projectId:projectId||((ui.project!=='all'&&project(ui.project))?ui.project:state.projects[0].id),assignee:state.profile.memberId,start:today(),end:addDays(today(),3),status:'todo',priority:'medium',description:'',dependsOn:''};
  const deps=()=>options([['','No dependency'],...state.tasks.filter(x=>x.projectId===t.projectId&&x.id!==t.id).map(x=>[x.id,x.title])],t.dependsOn);
  formDialog(id?'Edit task':'New task',field('Task title','title','text',t.title,'required maxlength="120"',true)+selectField('Project','projectId',projectOptions(t.projectId))+selectField('Assignee','assignee',memberOptions(t.assignee))+field('Start date','start','date',t.start,'required')+field('Due date','end','date',t.end,'required')+selectField('Status','status',options(Object.entries(STATUSES),t.status))+selectField('Priority','priority',options([['low','Low'],['medium','Medium'],['high','High']],t.priority))+selectField('Depends on','dependsOn',deps(),true)+textField('Notes / blocker','description',t.description),{kind:'task',id:t.id,existing:!!id},id?'delete-task':'');
  $('#f-projectId').addEventListener('change',e=>{$('#f-dependsOn').innerHTML=options([['','No dependency'],...state.tasks.filter(x=>x.projectId===e.target.value&&x.id!==t.id).map(x=>[x.id,x.title])],'');});
}
function projectDialog(id=''){const p=project(id)||{id:uid(),name:'',description:'',owner:state.profile.memberId,division:'Marketing, Communication & IT',start:today(),end:addDays(today(),14),color:state.projects.length%4};formDialog(id?'Edit project':'New project',field('Project name','name','text',p.name,'required maxlength="100"',true)+selectField('Division','division',options(DIVISIONS,p.division))+selectField('Project lead','owner',memberOptions(p.owner))+field('Start date','start','date',p.start,'required')+field('Target date','end','date',p.end,'required')+selectField('Artwork palette','color',options([['0','Peach & blue'],['1','Butter & sage'],['2','Sage & sky'],['3','Peach, butter & sage']],String(p.color)),true)+textField('Project description','description',p.description),{kind:'project',id:p.id,existing:!!id},id?'delete-project':'');}
function eventDialog(id='',date=''){const e=state.events.find(e=>e.id===id)||{id:uid(),title:'',projectId:ui.project==='all'?'':ui.project,date:date||(route().page==='calendar'?ui.selectedDay:today()),time:'09:00',duration:60,location:'',notes:''};formDialog(id?'Edit event':'New event',field('Event title','title','text',e.title,'required maxlength="120"',true)+selectField('Project','projectId',options([['','Personal / organization'],...state.projects.map(p=>[p.id,p.name])],e.projectId),true)+field('Date','date','date',e.date,'required')+field('Start time','time','time',e.time,'required')+field('Duration (minutes)','duration','number',e.duration,'required min="15" max="480" step="15"')+field('Location / meeting link','location','text',e.location,'maxlength="500"')+textField('Agenda / notes','notes',e.notes),{kind:'event',id:e.id,existing:!!id},id?'delete-event':'');}
function memberDialog(id=''){const m=member(id)||{id:uid(),name:''};formDialog(id?'Edit member':'Add a member',field('Display name','name','text',m.name,'required maxlength="60"',true),{kind:'member',id:m.id,existing:!!id});}
function clearFieldErrors(){document.querySelectorAll('.field-error').forEach(el=>el.remove());document.querySelectorAll('[aria-invalid]').forEach(el=>{el.removeAttribute('aria-invalid');el.removeAttribute('aria-describedby');});}
function formError(message){clearFieldErrors();const el=$('#form-error');el.hidden=false;el.className='form-error';el.textContent=message;const field=/dependency|dependent/i.test(message)?'dependsOn':/due date|end date|Project dates/i.test(message)?'end':/date and time/i.test(message)?'date':/duration/i.test(message)?'duration':/assignee/i.test(message)?'assignee':/lead/i.test(message)?'owner':/division/i.test(message)?'division':/title/i.test(message)?'title':/name/i.test(message)?'name':/project/i.test(message)?'projectId':'';const input=field&&document.querySelector(`#f-${field}`);if(input){const error=document.createElement('p');error.className='field-error';error.id=`error-${field}`;error.textContent=message;input.parentElement.append(error);input.setAttribute('aria-invalid','true');input.setAttribute('aria-describedby',error.id);input.focus();}else el.focus();}
document.addEventListener('submit',async e=>{if(e.target.id!=='edit-form')return;e.preventDefault();clearFieldErrors();$('#form-error').hidden=true;const c=dialogContext;const data=Object.fromEntries(new FormData(e.target));Object.keys(data).forEach(k=>data[k]=data[k].trim());data.id=c.id;let next=structuredClone(state),error='';
  if(c.kind==='task'){error=taskError(data,state);if(!error)next=applyTask(state,data);}
  if(c.kind==='project'){data.color=Number(data.color);error=projectError(data,state);if(!error){const ts=state.tasks.filter(t=>t.projectId===data.id);if(ts.length&&(ts.some(t=>t.start<data.start)||ts.some(t=>t.end>data.end)))error='Project dates must include existing tasks. Adjust task dates first or expand the project range.';}if(!error){const old=next.projects.findIndex(p=>p.id===data.id);if(old<0)next.projects.push(data);else next.projects[old]=data;}}
  if(c.kind==='event'){data.duration=Number(data.duration);error=eventError(data,state);if(!error){const old=next.events.findIndex(x=>x.id===data.id);if(old<0)next.events.push(data);else next.events[old]=data;}}
  if(c.kind==='member'){if(!data.name)error='Enter a display name.';data.initials=initials(data.name);if(!error){const old=next.members.findIndex(x=>x.id===data.id);if(old<0)next.members.push(data);else next.members[old]=data;if(data.id===next.profile.memberId)next.profile.name=data.name;}}
  if(error){formError(error);return;}const submit=e.target.querySelector('[type="submit"]');submit.disabled=true;submit.textContent='Saving…';try{if(await save(next,`${c.existing?'Updated':'Created'} ${c.kind}: ${data.title||data.name}`)){closeDialog();}else formError(appError||'The change could not be saved. Your draft is still here.');}finally{if(submit.isConnected){submit.disabled=false;submit.textContent=`Save ${c.kind}`;}}
});
function confirmDelete(kind,id){const item=(kind==='project'?state.projects:kind==='task'?state.tasks:state.events).find(x=>x.id===id);if(!item)return;$('#editor').close();const detail=kind==='project'?`This removes the project, its ${state.tasks.filter(t=>t.projectId===id).length} tasks, linked events, milestones, blockers, and documents.${sharedConfigured?' This shared deletion cannot be undone.':' You can undo this change.'}`:kind==='task'?'This also clears links from tasks that depend on it. You can undo this change.':'You can undo this change.';openDialog(`Delete ${kind}?`,`<div class="dialog-body"><p><strong>${h(item.name||item.title)}</strong></p><p class="muted small" style="margin-top:12px">${detail}</p></div>`,`<div class="dialog-actions">${button('Cancel','close-dialog')}${button('Delete '+kind,'confirm-delete',`data-kind="${kind}" data-id="${h(id)}"`,'danger')}</div>`,{kind:'confirm',id});}
async function changeStatus(id,status){const t=state.tasks.find(t=>t.id===id);if(!t)return;try{const result=await save(applyTask(state,{...t,status}),`${status==='done'?'Completed':'Updated'} task: ${t.title}`);if(!result)render();}catch(e){render();toast(e.message);}}
function monthShift(date,n){const d=day(date);return iso(new Date(d.getFullYear(),d.getMonth()+n,1));}
function exportBackup(){const text=sharedConfigured?localStorage.getItem(STORE_KEY):storageIssue&&rawBackup?rawBackup:JSON.stringify(state,null,2);if(!text){toast('No local v1 backup exists in this browser.');return;}const a=document.createElement('a');const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.href=url;a.download=`dwdg-workspace-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Local backup exported.');}
function legacyMapFromDialog(){return Object.fromEntries([...document.querySelectorAll('[data-legacy-member]')].filter(x=>x.value).map(x=>[x.dataset.legacyMember,x.value]));}
function showLegacyPreview(data,memberMap={},serverPreview=null,importId=crypto.randomUUID()){
  const preview=previewLegacyBackup(data,memberMap);
  const rows=data.members.map(m=>`<div class="v03-legacy-map-row"><span>${h(m.name)}</span><select data-legacy-member="${h(m.id)}" aria-label="Map ${h(m.name)} to invited member">${options([['','Choose account'],...state.members.map(x=>[x.id,x.name])],memberMap[m.id])}</select></div>`).join('');
  const issues=[...preview.unknownDivisions.map(x=>`Unknown division: ${h(x)}`),...preview.invalidLinks.map(x=>`Broken record link: ${h(x)}`)].map(x=>`<li>${x}</li>`).join('');
  const result=serverPreview?`<div class="notice" role="status"><strong>Server preview complete.</strong> ${h(JSON.stringify(serverPreview))}</div>`:'';
  if($('#editor').open)$('#editor').close();
  openDialog('Review old workspace backup',`<div class="dialog-body"><p>${preview.counts.projects} projects, ${preview.counts.tasks} tasks, and ${preview.counts.meetings} meetings. No records are uploaded until you commit.</p>${preview.renamedDivisions.length?'<p class="small muted">Client Engagement will be mapped to External Engagement.</p>':''}<h3>Match legacy names to invited accounts</h3><div class="v03-legacy-map">${rows}</div>${issues?`<ul class="notice error">${issues}</ul>`:''}${result}<p class="small muted">Review all mappings before importing. Existing browser data remains untouched.</p></div>`,`<div class="dialog-actions">${button('Cancel','close-dialog')}${button('Preview on server','preview-import','','primary')}${serverPreview&&preview.ready?button('Commit import','confirm-import','','primary'):''}</div>`,{kind:'legacy-import',data,memberMap,importId,serverPreview});
}
async function commitLegacyImport(){const c=dialogContext;if(!c||c.kind!=='legacy-import'||!c.serverPreview)return;const map=legacyMapFromDialog();const current=previewLegacyBackup(c.data,map);if(!current.ready){toast('Map every member before importing.');return;}if(JSON.stringify(map)!==JSON.stringify(c.memberMap)){showLegacyPreview(c.data,map,null,c.importId);toast('Mappings changed. Preview them again before committing.');return;}const buttonEl=$('[data-action="confirm-import"]');buttonEl.disabled=true;try{await sharedBackend.importLegacyBackup(c.data,map,false,c.importId);closeDialog();await refreshShared(true);toast('Legacy workspace imported.');}catch(error){buttonEl.disabled=false;toast(error.message);}}
function openMenu(){openDialog('Navigation',`<div class="dialog-body menu-panel">${[['home','Home','home'],['tasks','My Work','tasks'],['calendar','Schedule','calendar'],['updates','Updates','flag'],['projects','All Projects','projects'],['gantt','Timeline','gantt'],['settings','Settings','settings']].map(([id,label,i])=>`<a href="#${id}" data-menu-link>${icon(i)}${label}</a>`).join('')}<p class="nav-label">WORKSPACES</p>${divisionRoutes.map(([slug,label,i])=>`<a href="#workspace/${slug}" data-menu-link>${icon(i)}${h(label)}</a>`).join('')}</div>`);}
function openWorkspacesMenu(){openDialog('Choose workspace',`<div class="dialog-body menu-panel"><a href="#home" data-menu-link>${icon('home')}Personal Home</a>${divisionRoutes.map(([slug,label,i])=>`<a href="#workspace/${slug}" data-menu-link>${icon(i)}<span>${h(label)}${['external-engagement','consulting'].includes(slug)?'<small class="sub">Shared summary</small>':''}</span></a>`).join('')}</div>`);}
function searchResults(query){const q=query.trim().toLowerCase();if(!q)return '<p class="v03-empty">Search projects, tasks, and divisions.</p>';const found=[...state.projects.filter(p=>`${p.name} ${p.division}`.toLowerCase().includes(q)).map(p=>({label:p.name,meta:`Project · ${p.division}`,href:`#projects/${p.id}`})),...catalogOnly().filter(item=>`${item.name} ${catalogDivision(item)}`.toLowerCase().includes(q)).map(item=>({label:item.name,meta:`Shared summary · ${catalogDivision(item)}`,href:'#projects'})),...state.tasks.filter(t=>`${t.title} ${project(t.projectId)?.name||''}`.toLowerCase().includes(q)).map(t=>({label:t.title,meta:`Task · ${project(t.projectId)?.name||'Project'}`,href:'#tasks'})),...divisionRoutes.filter(([,label])=>label.toLowerCase().includes(q)).map(([slug,label])=>({label,meta:'Division workspace',href:`#workspace/${slug}`}))].slice(0,12);return found.length?found.map(x=>`<a class="v03-search-result" href="${h(x.href)}" data-menu-link><strong>${h(x.label)}</strong><span>${h(x.meta)}</span></a>`).join(''):'<p class="v03-empty">No permitted results match your search.</p>';}
function openGlobalSearch(){openDialog('Search workspace',`<div class="dialog-body"><label class="sr-only" for="global-search-input">Search projects, tasks, and divisions</label><input class="input" id="global-search-input" type="search" autocomplete="off" placeholder="Find a project, task, or division…"><div id="global-search-results" class="v03-search-results">${searchResults('')}</div></div>`);$('#global-search-input').focus();}
document.addEventListener('click',async e=>{if(e.target.closest('[data-menu-link]'))closeDialog();const b=e.target.closest('[data-action]');if(!b){const row=e.target.closest('[data-task-row]');if(row&&!e.target.closest('input,select,label,button,a')&&!window.getSelection()?.toString())taskDialog(row.dataset.taskRow);return;}const a=b.dataset.action,id=b.dataset.id;if(discardClick&&a==='edit-task'){discardClick=false;return;}
  switch(a){
    case 'new-task':taskDialog('',b.dataset.project);break;case 'edit-task':taskDialog(id);break;
    case 'new-project':projectDialog();break;case 'edit-project':projectDialog(id);break;
    case 'open-project':go('projects/'+id);break;case 'navigate':go(b.dataset.to);break;
    case 'new-event':eventDialog('',b.dataset.date);break;case 'edit-event':eventDialog(id);break;
    case 'new-member':memberDialog();break;case 'edit-member':memberDialog(id);break;
    case 'close-dialog':closeDialog();break;case 'undo':undo();break;
    case 'delete-task':confirmDelete('task',id);break;case 'delete-project':confirmDelete('project',id);break;case 'delete-event':confirmDelete('event',id);break;
    case 'confirm-delete':{const k=b.dataset.kind;let next=structuredClone(state);if(k==='task')next=deleteTask(state,id);if(k==='event')next.events=next.events.filter(x=>x.id!==id);if(k==='project'){next.projects=next.projects.filter(x=>x.id!==id);next.tasks=next.tasks.filter(x=>x.projectId!==id);next.events=next.events.filter(x=>x.projectId!==id);}b.disabled=true;if(await save(next,`Deleted ${k}.`)){closeDialog();if(k==='project')go('projects');}else b.disabled=false;break;}
    case 'mine':ui.assignee=ui.assignee===state.profile.memberId?'all':state.profile.memberId;render();break;
    case 'layout':ui.layout=b.dataset.layout;render();break;
    case 'project-timeline':go('gantt');ui.project=b.dataset.project;ui.gantt=project(b.dataset.project)?.start||today();render();break;
    case 'calendar-prev':ui.calendar=monthShift(ui.calendar,-1);ui.selectedDay=ui.calendar;render();break;case 'calendar-next':ui.calendar=monthShift(ui.calendar,1);ui.selectedDay=ui.calendar;render();break;case 'calendar-today':ui.calendar=today();ui.selectedDay=today();render();break;case 'select-day':ui.selectedDay=b.dataset.date;render();break;
    case 'calendar-mode':ui.calendarMode=b.dataset.mode;render();break;
    case 'day-agenda':openDialog(fullDate(b.dataset.date),`<div>${agendaRange(b.dataset.date,b.dataset.date)}</div>`);break;
    case 'zoom':ui.zoom=b.dataset.zoom;render();break;
    case 'gantt-prev':ui.gantt=ui.zoom==='month'?monthShift(ui.gantt,-1):addDays(ui.gantt,-14);render();break;
    case 'gantt-next':ui.gantt=ui.zoom==='month'?monthShift(ui.gantt,1):addDays(ui.gantt,14);render();break;
    case 'gantt-today':ui.gantt=today();render();break;
    case 'chart-range':ui.chartDays=Number(b.dataset.days)===30?30:7;render();document.querySelector(`[data-days="${ui.chartDays}"]`)?.focus();break;
    case 'chart-detail':{const date=b.dataset.date;const ts=state.tasks.filter(t=>t.status==='done'&&t.completedAt===date);$('#chart-note').textContent=`${fmt(date)} · ${ts.length} completed${ts.length?': '+ts.map(t=>t.title).join(', '):'.'}`;break;}
    case 'mobile-menu':openMenu();break;case 'workspaces-menu':openWorkspacesMenu();break;case 'global-search':openGlobalSearch();break;case 'settings':go('settings');break;case 'export':exportBackup();break;case 'import':$('#import-file').click();break;
    case 'sign-in':try{appError='';await sharedBackend.signInWithGoogle(location.href);}catch(error){appError=error.message;render();}break;
    case 'retry-session':try{appError='';if(!sharedBackend){await initializeShared();break;}sessionInfo=await sharedBackend.bootstrap();if(sessionInfo){await refreshShared(true);watchShared();}render();}catch(error){appError=error.message;render();}break;
    case 'switch-account':try{await sharedBackend.signOut();sessionInfo=null;await sharedBackend.signInWithGoogle(location.href);}catch(error){appError=error.message;render();}break;
    case 'sign-out':try{await sharedBackend.signOut();unsubscribeShared();sessionInfo=null;render();}catch(error){toast(error.message);}break;
    case 'revoke-invite':if(!sessionInfo?.canManageInvitations)break;try{b.disabled=true;await sharedBackend.revokeInvitation(b.dataset.email);invitations=await sharedBackend.listInvitations();render();toast('Invitation revoked.');}catch(error){b.disabled=false;toast(error.message);}break;
    case 'mark-notification':if(!sharedBackend)break;try{b.disabled=true;await sharedBackend.markNotificationRead(id);notifications=await sharedBackend.listNotifications();render();}catch(error){b.disabled=false;toast(error.message);}break;
    case 'load-project-access':if(!sessionInfo?.canManageInvitations)break;try{const selected=$('#project-access-form [name="projectId"]')?.value;if(!selected)throw new Error('Choose a project first.');b.disabled=true;projectAccess=await sharedBackend.listProjectAccess(selected);accessProjectId=selected;render();}catch(error){b.disabled=false;toast(error.message);}break;
    case 'remove-project-access':if(!sessionInfo?.canManageInvitations)break;try{b.disabled=true;await sharedBackend.removeProjectAccess(b.dataset.project,b.dataset.user);projectAccess=await sharedBackend.listProjectAccess(b.dataset.project);render();toast('Project access removed.');}catch(error){b.disabled=false;toast(error.message);}break;
    case 'preview-import':{const c=dialogContext;if(!c||c.kind!=='legacy-import')break;const map=legacyMapFromDialog();const preview=previewLegacyBackup(c.data,map);if(!preview.ready){toast('Map every member and resolve backup errors first.');showLegacyPreview(c.data,map,null,c.importId);break;}b.disabled=true;try{const result=await sharedBackend.importLegacyBackup(c.data,map,true,c.importId);showLegacyPreview(c.data,map,result,c.importId);}catch(error){b.disabled=false;toast(error.message);}break;}
    case 'confirm-import':{if(sharedConfigured){await commitLegacyImport();break;}const next=dialogContext.data;if(await save(next,'Imported workspace backup.')){closeDialog();go('home');}break;}
    case 'recover':openDialog('Replace unreadable saved data?',`<div class="dialog-body"><p>Export the original backup first if you want to keep it. This saves the current session as your browser workspace.</p></div>`,`<div class="dialog-actions">${button('Cancel','close-dialog')}${button('Save current session','confirm-recover','','primary')}</div>`);break;
    case 'confirm-recover':try{localStorage.setItem(STORE_KEY,JSON.stringify(state));storageIssue='';rawBackup='';closeDialog();render();toast('Current workspace saved.');}catch{toast('Browser storage is unavailable. Export a backup to keep this session.');}break;
  }
});
document.addEventListener('input',e=>{if(e.target.closest('.field')&&e.target.hasAttribute('aria-invalid')){e.target.removeAttribute('aria-invalid');e.target.removeAttribute('aria-describedby');e.target.closest('.field').querySelector('.field-error')?.remove();}if(e.target.matches('[data-search]')){ui.search=e.target.value;render();}if(e.target.id==='global-search-input')$('#global-search-results').innerHTML=searchResults(e.target.value);});
document.addEventListener('change',e=>{if(e.target.dataset.statusTask){const id=e.target.dataset.statusTask;changeStatus(id,e.target.value);const controls=[...document.querySelectorAll('[data-status-task]')];controls.find(x=>x.dataset.statusTask===id&&x.getClientRects().length)?.focus();return;}const f=e.target.dataset.filter;if(f){ui[f]=e.target.value;render();}if(e.target.dataset.complete)changeStatus(e.target.dataset.complete,e.target.checked?'done':'todo');});
$('#import-file').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>3*1024*1024)throw new Error('Backup must be smaller than 3 MB.');const data=JSON.parse(await file.text());if(!validateState(data))throw new Error('This file is not a valid DWDG workspace backup.');if(sharedConfigured){if(!sessionInfo?.canManageInvitations)throw new Error('Only a Super Admin can import a legacy backup.');showLegacyPreview(data);return;}openDialog('Import workspace?',`<div class="dialog-body"><p>This replaces your current workspace with ${data.projects.length} projects, ${data.tasks.length} tasks, and ${data.events.length} events.</p><p class="muted small" style="margin-top:12px">Export your current workspace first if you want a separate backup. Import can also be undone immediately.</p></div>`,`<div class="dialog-actions">${button('Cancel','close-dialog')}${button('Import workspace','confirm-import','','primary')}</div>`,{kind:'import',data});}catch(err){toast(err.message);}});
$('#editor').addEventListener('cancel',()=>{dialogContext=null;});
$('#editor').addEventListener('click',e=>{if(e.target===$('#editor')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});
let draggedId='';document.addEventListener('dragstart',e=>{const card=e.target.closest('[data-drag-task]');if(card){draggedId=card.dataset.dragTask;e.dataTransfer.setData('text/plain',draggedId);e.dataTransfer.effectAllowed='move';}});
document.addEventListener('dragover',e=>{const col=e.target.closest('[data-drop-status]');if(col&&draggedId){e.preventDefault();col.classList.add('drag-over');}});
document.addEventListener('dragleave',e=>{const col=e.target.closest('[data-drop-status]');if(col&&!col.contains(e.relatedTarget))col.classList.remove('drag-over');});
document.addEventListener('drop',e=>{const col=e.target.closest('[data-drop-status]');if(col&&draggedId){e.preventDefault();changeStatus(draggedId,col.dataset.dropStatus);draggedId='';}});
document.addEventListener('dragend',()=>{draggedId='';document.querySelectorAll('.drag-over').forEach(el=>el.classList.remove('drag-over'));});
document.addEventListener('keydown',async e=>{const bar=e.target.closest('[data-gantt-task]');if(!bar)return;if(e.key==='Enter'||e.key===' '){e.preventDefault();taskDialog(bar.dataset.ganttTask);}if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const id=bar.dataset.ganttTask;try{const next=shiftTask(state,id,e.key==='ArrowRight'?1:-1,e.shiftKey);const saved=await save(next,'Rescheduled task: '+state.tasks.find(t=>t.id===id).title);if(!saved)render();document.querySelector(`[data-gantt-task="${CSS.escape(id)}"]`)?.focus();}catch(err){render();toast(err.message);}}});
document.addEventListener('pointerdown',e=>{const bar=e.target.closest('[data-gantt-task]');if(!bar||e.button!==0)return;const id=bar.dataset.ganttTask;const resize=!!e.target.closest('.resize-handle');const startX=e.clientX;const initialLeft=parseFloat(bar.style.left),initialWidth=parseFloat(bar.style.width);let delta=0,moved=false;bar.setPointerCapture(e.pointerId);
  const move=ev=>{if(Math.abs(ev.clientX-startX)<5&&!moved)return;moved=true;bar.classList.add('dragging');delta=Math.round((ev.clientX-startX)/ganttRange().width);if(resize)bar.style.width=Math.max(12,initialWidth+delta*ganttRange().width)+'px';else bar.style.left=initialLeft+delta*ganttRange().width+'px';};
  const finish=async()=>{bar.removeEventListener('pointermove',move);bar.removeEventListener('pointerup',finish);bar.removeEventListener('pointercancel',cancel);bar.classList.remove('dragging');if(!moved)return;discardClick=true;setTimeout(()=>discardClick=false,100);if(delta){try{const next=shiftTask(state,id,delta,resize);if(!await save(next,'Rescheduled task: '+state.tasks.find(t=>t.id===id).title))render();}catch(err){render();toast(err.message);}}else render();};
  const cancel=()=>{bar.removeEventListener('pointermove',move);bar.removeEventListener('pointerup',finish);bar.removeEventListener('pointercancel',cancel);render();};bar.addEventListener('pointermove',move);bar.addEventListener('pointerup',finish);bar.addEventListener('pointercancel',cancel);
});
window.addEventListener('hashchange',()=>{ui.search='';ui.status='all';ui.assignee=route().page==='tasks'?state.profile.memberId:'all';if(route().page!=='gantt')ui.project='all';ui.division='all';render();window.scrollTo({top:0,left:0,behavior:'instant'});});
window.addEventListener('storage',e=>{if(sharedConfigured||e.key!==STORE_KEY||!e.newValue)return;try{const updated=JSON.parse(e.newValue);if(validateState(updated)){state=updated;undoState=null;render();toast('Workspace updated in another tab.');}}catch{}});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(!$('#editor').open)openGlobalSearch();}});
if(route().page==='tasks')ui.assignee=state.profile.memberId;
mountPrism(document);
render();
if(sharedConfigured)initializeShared();

document.addEventListener('submit',async event=>{
  const form=event.target;if(!['invite-form','membership-form','remove-membership-form','role-form','approver-form','project-access-form'].includes(form.id))return;
  event.preventDefault();if(!sessionInfo?.canManageInvitations)return;
  const data=Object.fromEntries(new FormData(form));const submit=form.querySelector('[type="submit"]');const errorEl=form.querySelector('.v03-form-error');errorEl.hidden=true;submit.disabled=true;
  try{
    if(form.id==='invite-form'){await sharedBackend.createInvitation(data);invitations=await sharedBackend.listInvitations();toast('Invitation created. The member can now sign in with Google.');}
    else if(form.id==='membership-form'){await sharedBackend.setMembership(data.userId,data.divisionCode,data.role);toast('Division membership updated.');}
    else if(form.id==='remove-membership-form'){await sharedBackend.removeMembership(data.userId,data.divisionCode);toast('Division membership removed.');}
    else if(form.id==='role-form'){await sharedBackend.setGlobalRole(data.userId,data.role,data.active==='true');toast('Account access updated.');}
    else if(form.id==='approver-form'){await sharedBackend.setFinanceApprover(data.userId,data.enabled==='true');toast('Finance approval access updated.');}
    else if(form.id==='project-access-form'){await sharedBackend.setProjectAccess(data.projectId,data.userId,data.role);accessProjectId=data.projectId;projectAccess=await sharedBackend.listProjectAccess(data.projectId);toast('Project access updated.');}
    if(form.id!=='invite-form')accessRoster=await sharedBackend.listMembersWithAccess();
    render();
  }catch(error){errorEl.textContent=error.message;errorEl.hidden=false;submit.disabled=false;}
});

function adminSettingsPage(){
  if(!sharedConfigured||!sessionInfo?.canManageInvitations)return '';
  const inviteRows=invitations.slice(0,15).map(x=>`<div class="v03-row"><div class="v03-row-main"><strong>${h(x.email)}</strong><span class="sub">${h(x.primary_division_code||'Organization')} · ${h(x.division_role||'member')}</span></div><span class="v03-badge" data-tone="${x.revoked_at?'warning':'success'}">${x.revoked_at?'Revoked':'Invited'}</span>${x.revoked_at?'':button('Revoke','revoke-invite',`data-email="${h(x.email)}"`)}</div>`).join('')||'<div class="v03-empty">No invitations yet.</div>';
  const members=accessRoster.profiles.map(x=>`<div class="v03-row"><div class="v03-row-main"><strong>${h(x.full_name||x.email)}</strong><span class="sub">${h(x.email)} · ${h(x.global_role)} · ${accessRoster.memberships.filter(m=>m.user_id===x.id).map(m=>h(m.division_code)+' ('+h(m.role)+')').join(', ')||'No division membership'}</span></div></div>`).join('')||'<div class="v03-empty">No signed-in members yet.</div>';
  const divisions=divisionRoutes.map(([,label])=>[DIVISION_CODES[label],label]);
  return `<section class="v03-admin-access"><div class="v03-page-head"><div><span class="v03-eyebrow">SUPER ADMIN</span><h2>Access and invitations</h2><p>Only invited Google accounts can join. Membership controls editing; visibility follows database permissions.</p></div></div><div class="v03-grid-2"><section class="v03-panel"><div class="v03-panel-head"><h3>Invite a member</h3></div><form id="invite-form" class="v03-admin-form"><div class="v03-form-error" role="alert" hidden></div><label>Email<input class="input" name="email" type="email" autocomplete="email" required></label><label>Primary division<select name="divisionCode">${options(divisions,'strategy_growth')}</select></label><label>Division role<select name="divisionRole">${options([['viewer','Viewer'],['member','Member'],['division_head','Division head']],'member')}</select></label><button class="button primary" type="submit">Create invitation</button></form><div class="v03-list">${inviteRows}</div></section><section class="v03-panel"><div class="v03-panel-head"><h3>Member access</h3></div><form id="membership-form" class="v03-admin-form"><div class="v03-form-error" role="alert" hidden></div><label>Member<select name="userId">${options(state.members.map(x=>[x.id,x.name]),'')}</select></label><label>Division<select name="divisionCode">${options(divisions,'strategy_growth')}</select></label><label>Role<select name="role">${options([['viewer','Viewer'],['member','Member'],['division_head','Division head']],'member')}</select></label><button class="button primary" type="submit">Update membership</button></form><div class="v03-list">${members}</div></section></div></section>`;
}
function adminManagementPanels(){
  if(!sharedConfigured||!sessionInfo?.canManageInvitations)return '';
  const people=options(accessRoster.profiles.map(p=>[p.id,p.full_name||p.email]),'');
  const divisions=options(divisionRoutes.map(([,label])=>[DIVISION_CODES[label],label]),'');
  const projects=options(state.projects.map(p=>[p.id,p.name]),accessProjectId);
  const grants=projectAccess.map(grant=>`<div class="v03-row"><div class="v03-row-main"><strong>${h(accessRoster.profiles.find(p=>p.id===grant.user_id)?.full_name||grant.user_id)}</strong><span class="sub">${h(grant.role)}</span></div>${button('Remove','remove-project-access',`data-project="${h(grant.project_id)}" data-user="${h(grant.user_id)}"`)}</div>`).join('')||'<div class="v03-empty">No direct access grants loaded for this project.</div>';
  return `<div class="v03-admin-access v03-grid-2">
    <section class="v03-panel"><div class="v03-panel-head"><h3>Member roles</h3></div>
      <form id="role-form" class="v03-admin-form"><div class="v03-form-error" role="alert" hidden></div><label>Member<select name="userId" required>${people}</select></label><label>Organization role<select name="role">${options([['member','Member'],['super_admin','Super Admin']],'member')}</select></label><label>Account<select name="active">${options([['true','Active'],['false','Inactive']],'true')}</select></label><button class="button primary" type="submit">Update account</button></form>
      <form id="approver-form" class="v03-admin-form"><div class="v03-form-error" role="alert" hidden></div><label>Member<select name="userId" required>${people}</select></label><label>Finance approval<select name="enabled">${options([['true','Designated approver'],['false','No approval access']],'true')}</select></label><button class="button primary" type="submit">Update approver</button></form>
      <form id="remove-membership-form" class="v03-admin-form"><div class="v03-form-error" role="alert" hidden></div><label>Member<select name="userId" required>${people}</select></label><label>Division<select name="divisionCode">${divisions}</select></label><button class="button" type="submit">Remove membership</button></form>
    </section>
    <section class="v03-panel"><div class="v03-panel-head"><h3>Project access</h3></div>
      <form id="project-access-form" class="v03-admin-form"><div class="v03-form-error" role="alert" hidden></div><label>Project<select name="projectId" required>${projects}</select></label><label>Member<select name="userId" required>${people}</select></label><label>Access<select name="role">${options([['viewer','Viewer'],['editor','Editor'],['lead','Lead']],'viewer')}</select></label><div class="actions"><button class="button primary" type="submit">Grant access</button>${button('View grants','load-project-access','type="button"')}</div></form>
      <div class="v03-list">${grants}</div>
    </section>
  </div>`;
}
function notificationPanel(){
  if(!sharedConfigured)return '';
  const rows=notifications.slice(0,30).map(n=>`<div class="v03-row ${n.read_at?'':'v03-unread'}"><span class="v03-activity-mark"></span><div class="v03-row-main"><strong>${h(n.title)}</strong><span class="sub">${h(new Date(n.created_at).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'}))}</span></div>${n.read_at?'':button('Mark read','mark-notification',`data-id="${h(n.id)}"`)}</div>`).join('');
  return `<section class="v03-panel v03-notifications"><div class="v03-panel-head"><h2>Notifications</h2><span class="v03-count">${notifications.filter(n=>!n.read_at).length} unread</span></div><div class="v03-list">${rows||'<div class="v03-empty"><strong>You are all caught up.</strong><span>Approvals, assignments, and relevant updates will appear here.</span></div>'}</div></section>`;
}
